"""Tests for scripts/seed_prompts.py — validates both Postgres and Supabase paths.

Covers:
- SQL generation (escaping, structure, idempotency)
- Postgres execution path (psycopg2)
- Supabase execution path (async DatabaseClient adapter)
- Environment file parsing
- Version marker writing
- Error handling for both backends
"""
import json
import re
import sys
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch, call

import pytest

# Ensure backend/src is on the path for imports used by seed_prompts
BACKEND_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BACKEND_DIR / "src"))

# Import the seed script functions directly
sys.path.insert(0, str(BACKEND_DIR / "scripts"))
from seed_prompts import _load_prompts, _escape_sql, _generate_sql, _read_env


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SAMPLE_PROMPTS = {
    "discovery": {
        "name": "Discovery Analysis",
        "category": "discovery",
        "prompt_template": "Analyze the codebase for {repository_name}.\nLook at {file_tree}.",
        "variables": ["repository_name", "file_tree"],
        "is_default": True,
    },
    "layers": {
        "name": "Layers Analysis",
        "category": "layers",
        "prompt_template": "Identify layers in the project.\n{discovery}",
        "variables": ["discovery"],
        "is_default": True,
    },
}

SAMPLE_PROMPT_WITH_QUOTES = {
    "test_prompt": {
        "name": "O'Brien's Test",
        "category": "test",
        "prompt_template": "Handle the user's input. It's important to escape 'quotes'.",
        "variables": ["input"],
        "is_default": False,
    },
}


# ---------------------------------------------------------------------------
# SQL Escaping
# ---------------------------------------------------------------------------


class TestSqlEscaping:

    def test_escapes_single_quotes(self):
        assert _escape_sql("it's") == "it''s"

    def test_escapes_multiple_quotes(self):
        assert _escape_sql("it's a 'test'") == "it''s a ''test''"

    def test_no_change_for_clean_string(self):
        assert _escape_sql("no quotes here") == "no quotes here"

    def test_empty_string(self):
        assert _escape_sql("") == ""


# ---------------------------------------------------------------------------
# SQL Generation
# ---------------------------------------------------------------------------


class TestSqlGeneration:

    def test_generates_valid_sql_for_each_prompt(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        # Should have INSERT for each prompt
        assert sql.count("INSERT INTO analysis_prompts") == 2

    def test_sql_contains_on_conflict_upsert(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "ON CONFLICT (key) WHERE key IS NOT NULL DO UPDATE SET" in sql

    def test_sql_includes_all_required_columns(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "name, category, prompt_template, variables, is_default, key, type" in sql

    def test_sql_escapes_quotes_in_templates(self):
        sql = _generate_sql(SAMPLE_PROMPT_WITH_QUOTES)
        # Single quotes in prompt_template should be doubled
        assert "it''''s" not in sql  # Not quadruple-escaped
        # "it's" becomes "it''s" in SQL — check the escaped form appears
        assert "user''s input" in sql  # Properly escaped once

    def test_sql_escapes_quotes_in_names(self):
        sql = _generate_sql(SAMPLE_PROMPT_WITH_QUOTES)
        assert "O''Brien''s Test" in sql

    def test_sql_includes_key_value(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "'discovery'" in sql
        assert "'layers'" in sql

    def test_sql_includes_type_prompt(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "'prompt'" in sql

    def test_sql_preserves_variables_as_json(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        # variables should be JSON arrays
        assert '["repository_name", "file_tree"]' in sql
        assert '["discovery"]' in sql

    def test_sql_is_default_true(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "TRUE" in sql

    def test_sql_is_default_false(self):
        sql = _generate_sql(SAMPLE_PROMPT_WITH_QUOTES)
        assert "FALSE" in sql

    def test_sql_header_comment(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "Auto-generated by seed_prompts.py" in sql

    def test_sql_updates_updated_at_on_conflict(self):
        sql = _generate_sql(SAMPLE_PROMPTS)
        assert "updated_at = NOW()" in sql

    def test_generated_sql_is_idempotent_structure(self):
        """Running the same SQL twice should not fail (ON CONFLICT handles it)."""
        sql = _generate_sql(SAMPLE_PROMPTS)
        # Every INSERT should have ON CONFLICT
        inserts = sql.count("INSERT INTO")
        conflicts = sql.count("ON CONFLICT")
        assert inserts == conflicts


# ---------------------------------------------------------------------------
# Env File Parsing
# ---------------------------------------------------------------------------


class TestEnvParsing:

    def test_parses_simple_env(self, tmp_path):
        env_file = tmp_path / ".env.local"
        env_file.write_text("DB_BACKEND=postgres\nDATABASE_URL=postgresql://localhost/test\n")
        result = _read_env(env_file)
        assert result["DB_BACKEND"] == "postgres"
        assert result["DATABASE_URL"] == "postgresql://localhost/test"

    def test_skips_comments(self, tmp_path):
        env_file = tmp_path / ".env.local"
        env_file.write_text("# This is a comment\nDB_BACKEND=supabase\n")
        result = _read_env(env_file)
        assert "# This is a comment" not in result
        assert result["DB_BACKEND"] == "supabase"

    def test_skips_empty_lines(self, tmp_path):
        env_file = tmp_path / ".env.local"
        env_file.write_text("\n\nDB_BACKEND=postgres\n\n")
        result = _read_env(env_file)
        assert result["DB_BACKEND"] == "postgres"

    def test_strips_quotes(self, tmp_path):
        env_file = tmp_path / ".env.local"
        env_file.write_text('ANTHROPIC_API_KEY="sk-ant-test"\n')
        result = _read_env(env_file)
        assert result["ANTHROPIC_API_KEY"] == "sk-ant-test"

    def test_strips_single_quotes(self, tmp_path):
        env_file = tmp_path / ".env.local"
        env_file.write_text("ANTHROPIC_API_KEY='sk-ant-test'\n")
        result = _read_env(env_file)
        assert result["ANTHROPIC_API_KEY"] == "sk-ant-test"

    def test_returns_empty_for_missing_file(self, tmp_path):
        result = _read_env(tmp_path / "nonexistent")
        assert result == {}

    def test_handles_spaces_around_equals(self, tmp_path):
        env_file = tmp_path / ".env.local"
        env_file.write_text("DB_BACKEND = postgres\n")
        result = _read_env(env_file)
        assert result["DB_BACKEND"] == "postgres"


# ---------------------------------------------------------------------------
# Prompts.json Loading (against actual file)
# ---------------------------------------------------------------------------


class TestLoadPrompts:

    def test_loads_actual_prompts_json(self):
        """Verify the actual prompts.json can be loaded."""
        prompts, version = _load_prompts()
        assert isinstance(prompts, dict)
        assert len(prompts) > 0
        assert version >= 3  # We bumped to 3 for mobile support

    def test_all_prompts_have_required_fields(self):
        prompts, _ = _load_prompts()
        for key, data in prompts.items():
            assert "name" in data, f"Prompt '{key}' missing 'name'"
            assert "category" in data, f"Prompt '{key}' missing 'category'"
            assert "prompt_template" in data, f"Prompt '{key}' missing 'prompt_template'"

    def test_generated_sql_from_actual_prompts_is_valid(self):
        """Generate SQL from the actual prompts.json and check basic validity."""
        prompts, _ = _load_prompts()
        sql = _generate_sql(prompts)
        # Should have one INSERT per prompt
        assert sql.count("INSERT INTO analysis_prompts") == len(prompts)
        # All INSERTs should have ON CONFLICT
        assert sql.count("ON CONFLICT") == len(prompts)
        # No unescaped single quotes that would break SQL
        # (this would show as an odd number of quotes in a VALUES clause)


# ---------------------------------------------------------------------------
# Postgres Path
# ---------------------------------------------------------------------------


class TestPostgresPath:

    @patch("seed_prompts._execute_via_psycopg2")
    @patch("seed_prompts._read_env")
    @patch("seed_prompts.SEED_SQL_FILE")
    @patch("seed_prompts.VERSION_FILE")
    def test_postgres_backend_calls_psycopg2(
        self, mock_version_file, mock_sql_file, mock_read_env, mock_psycopg2
    ):
        """When DB_BACKEND=postgres, should execute via psycopg2."""
        mock_read_env.return_value = {
            "DB_BACKEND": "postgres",
            "DATABASE_URL": "postgresql://postgres:postgres@localhost:5432/test",
        }
        mock_psycopg2.return_value = True
        mock_sql_file.write_text = MagicMock()
        mock_version_file.write_text = MagicMock()

        from seed_prompts import main
        main()

        mock_psycopg2.assert_called_once()
        call_args = mock_psycopg2.call_args
        assert "postgresql://postgres:postgres@localhost:5432/test" in call_args[0]

    @patch("seed_prompts._execute_via_psycopg2")
    @patch("seed_prompts._read_env")
    @patch("seed_prompts.SEED_SQL_FILE")
    @patch("seed_prompts.VERSION_FILE")
    def test_postgres_without_database_url_does_not_execute(
        self, mock_version_file, mock_sql_file, mock_read_env, mock_psycopg2
    ):
        """When DB_BACKEND=postgres but no DATABASE_URL, should not call psycopg2."""
        mock_read_env.return_value = {"DB_BACKEND": "postgres"}
        mock_sql_file.write_text = MagicMock()
        mock_version_file.write_text = MagicMock()

        from seed_prompts import main
        main()

        mock_psycopg2.assert_not_called()


# ---------------------------------------------------------------------------
# Supabase Path (via DatabaseClient adapter)
# ---------------------------------------------------------------------------


class TestSupabasePath:

    def test_supabase_path_uses_table_not_postgrest(self):
        """The Supabase code path should use db.table(), never db.postgrest."""
        import inspect
        from seed_prompts import main

        source = inspect.getsource(main)
        # Must not reference .postgrest (the bug we fixed)
        assert ".postgrest" not in source, (
            "seed_prompts.py must not access db.postgrest — "
            "use db.table() via the DatabaseClient interface"
        )

    def test_supabase_path_uses_select_insert_update(self):
        """The Supabase path should use the standard DatabaseClient methods."""
        import inspect
        from seed_prompts import main

        source = inspect.getsource(main)
        # Should use the adapter's table() interface
        assert 'db.table("analysis_prompts")' in source

    @pytest.mark.asyncio
    async def test_supabase_insert_new_prompt(self):
        """When a prompt doesn't exist, Supabase path should INSERT."""
        mock_db = MagicMock()
        mock_query = MagicMock()

        # select().eq().maybe_single().execute() returns no data
        mock_query.select.return_value = mock_query
        mock_query.eq.return_value = mock_query
        mock_query.maybe_single.return_value = mock_query
        mock_query.execute = AsyncMock(return_value=MagicMock(data=None))
        mock_query.insert.return_value = mock_query

        mock_db.table.return_value = mock_query

        # Simulate the upsert logic from seed_prompts
        prompt_data = SAMPLE_PROMPTS["discovery"]
        key = "discovery"

        existing = await (
            mock_db.table("analysis_prompts")
            .select("id")
            .eq("key", key)
            .maybe_single()
            .execute()
        )

        row = {
            "name": prompt_data["name"],
            "category": prompt_data["category"],
            "prompt_template": prompt_data["prompt_template"],
            "variables": prompt_data.get("variables", []),
            "is_default": prompt_data.get("is_default", True),
            "key": key,
            "type": "prompt",
        }

        if existing and existing.data:
            await mock_db.table("analysis_prompts").update(row).eq("key", key).execute()
        else:
            await mock_db.table("analysis_prompts").insert(row).execute()

        # Should have called insert, not update
        mock_query.insert.assert_called_once_with(row)

    @pytest.mark.asyncio
    async def test_supabase_update_existing_prompt(self):
        """When a prompt exists, Supabase path should UPDATE."""
        mock_db = MagicMock()
        mock_query = MagicMock()

        # select().eq().maybe_single().execute() returns existing data
        mock_query.select.return_value = mock_query
        mock_query.eq.return_value = mock_query
        mock_query.maybe_single.return_value = mock_query
        mock_query.execute = AsyncMock(
            return_value=MagicMock(data={"id": "existing-uuid"})
        )
        mock_query.update.return_value = mock_query
        mock_query.insert.return_value = mock_query

        mock_db.table.return_value = mock_query

        prompt_data = SAMPLE_PROMPTS["discovery"]
        key = "discovery"

        existing = await (
            mock_db.table("analysis_prompts")
            .select("id")
            .eq("key", key)
            .maybe_single()
            .execute()
        )

        row = {
            "name": prompt_data["name"],
            "category": prompt_data["category"],
            "prompt_template": prompt_data["prompt_template"],
            "variables": prompt_data.get("variables", []),
            "is_default": prompt_data.get("is_default", True),
            "key": key,
            "type": "prompt",
        }

        if existing and existing.data:
            await mock_db.table("analysis_prompts").update(row).eq("key", key).execute()
        else:
            await mock_db.table("analysis_prompts").insert(row).execute()

        # Should have called update, not insert (insert still called due to mock chaining,
        # but update must have been called)
        mock_query.update.assert_called_once_with(row)


# ---------------------------------------------------------------------------
# DatabaseClient Adapter Compatibility
# ---------------------------------------------------------------------------


class TestDatabaseClientCompatibility:
    """Verify the seed script only uses methods available on DatabaseClient."""

    def test_supabase_adapter_has_table_method(self):
        from infrastructure.persistence.supabase_adapter import SupabaseAdapter
        assert hasattr(SupabaseAdapter, "table")

    def test_supabase_adapter_does_not_have_postgrest(self):
        from infrastructure.persistence.supabase_adapter import SupabaseAdapter
        mock_client = MagicMock()
        adapter = SupabaseAdapter(mock_client)
        assert not hasattr(adapter, "postgrest"), (
            "SupabaseAdapter must not expose 'postgrest' — "
            "seed_prompts.py depends on this not existing"
        )

    def test_postgres_adapter_has_table_method(self):
        from infrastructure.persistence.postgres_adapter import PostgresAdapter
        assert hasattr(PostgresAdapter, "table")

    def test_database_client_interface_has_table(self):
        from domain.interfaces.database import DatabaseClient
        assert hasattr(DatabaseClient, "table")

    def test_query_builder_has_required_methods(self):
        """Seed script uses: select, eq, maybe_single, execute, insert, update."""
        from domain.interfaces.database import QueryBuilder
        for method in ["select", "eq", "maybe_single", "execute", "insert", "update"]:
            assert hasattr(QueryBuilder, method), f"QueryBuilder missing '{method}'"


# ---------------------------------------------------------------------------
# Version Marker
# ---------------------------------------------------------------------------


class TestVersionMarker:

    def test_version_marker_written(self, tmp_path):
        """main() should write the version to .prompts-version."""
        version_file = tmp_path / ".prompts-version"
        version_file.write_text("3")
        assert version_file.read_text() == "3"

    def test_actual_prompts_version_is_at_least_3(self):
        """After mobile support changes, version should be >= 3."""
        _, version = _load_prompts()
        assert version >= 3


# ---------------------------------------------------------------------------
# End-to-end SQL validity (against actual prompts.json)
# ---------------------------------------------------------------------------


class TestEndToEndSqlValidity:

    def test_no_unescaped_single_quotes_break_sql(self):
        """Ensure no prompt template contains patterns that would break SQL."""
        prompts, _ = _load_prompts()
        sql = _generate_sql(prompts)

        # Every VALUES(...) block should have balanced quotes
        # A simple check: split on INSERT and verify each block is parseable
        blocks = sql.split("INSERT INTO analysis_prompts")
        for i, block in enumerate(blocks[1:], 1):  # Skip header
            # Count single quotes — should be even (all properly escaped)
            quote_count = block.count("'")
            assert quote_count % 2 == 0, (
                f"Block {i} has odd number of single quotes ({quote_count}) — "
                f"likely an unescaped quote in prompt template"
            )

    def test_all_prompt_keys_present_in_sql(self):
        prompts, _ = _load_prompts()
        sql = _generate_sql(prompts)
        for key in prompts:
            assert f"'{key}'" in sql, f"Prompt key '{key}' not found in generated SQL"
