"""Seed analysis_prompts table from prompts.json.

Reads prompts.json (the single source of truth for prompt content),
generates an idempotent SQL file, and executes it against the database.

For Supabase users: the generated SQL is saved to
backend/migrations/seed_prompts.sql so it can be pasted into the SQL editor.

Usage:
    cd backend && PYTHONPATH=src python scripts/seed_prompts.py
"""
import json
import os
import re
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).parent.parent
PROMPTS_FILE = BACKEND_DIR / "prompts.json"
SEED_SQL_FILE = BACKEND_DIR / "migrations" / "seed_prompts.sql"
VERSION_FILE = BACKEND_DIR / ".prompts-version"


def _load_prompts() -> tuple[dict, int]:
    """Load prompts.json and return (prompts_dict, version)."""
    if not PROMPTS_FILE.exists():
        print(f"Error: {PROMPTS_FILE} not found")
        sys.exit(1)

    with open(PROMPTS_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    prompts = data.get("prompts", {})
    version = data.get("version", 0)
    if not prompts:
        print("No prompts found in prompts.json")
        sys.exit(1)

    return prompts, version


def _escape_sql(text: str) -> str:
    """Escape a string for use in a SQL single-quoted literal."""
    return text.replace("'", "''")


def _generate_sql(prompts: dict) -> str:
    """Generate idempotent SQL that upserts all prompts."""
    lines = [
        "-- Auto-generated by seed_prompts.py from prompts.json",
        "-- Do not edit manually — re-run: cd backend && PYTHONPATH=src python scripts/seed_prompts.py",
        "",
    ]

    for key, prompt_data in prompts.items():
        name = _escape_sql(prompt_data["name"])
        category = _escape_sql(prompt_data["category"])
        template = _escape_sql(prompt_data["prompt_template"])
        variables = json.dumps(prompt_data.get("variables", []))
        is_default = "TRUE" if prompt_data.get("is_default", True) else "FALSE"

        lines.append(f"""INSERT INTO analysis_prompts (name, category, prompt_template, variables, is_default, key, type)
VALUES (
    '{name}',
    '{category}',
    '{template}',
    '{variables}'::jsonb,
    {is_default},
    '{_escape_sql(key)}',
    'prompt'
)
ON CONFLICT (key) WHERE key IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    prompt_template = EXCLUDED.prompt_template,
    variables = EXCLUDED.variables,
    is_default = EXCLUDED.is_default,
    updated_at = NOW();
""")

    return "\n".join(lines)


def _read_env(env_file: Path) -> dict[str, str]:
    """Parse a .env file into a dict (simple key=value, no multiline)."""
    env = {}
    if not env_file.exists():
        return env
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r'^([A-Z_]+)\s*=\s*(.*)$', line)
        if match:
            k, v = match.group(1), match.group(2).strip().strip('"').strip("'")
            env[k] = v
    return env


def _execute_via_psycopg2(database_url: str, sql: str) -> bool:
    """Execute SQL via psycopg2 (sync, for local postgres)."""
    try:
        import psycopg2  # noqa: F811
    except ImportError:
        print("  psycopg2 not installed — trying psycopg2-binary...")
        try:
            import psycopg2  # noqa: F811
        except ImportError:
            return False

    try:
        conn = psycopg2.connect(database_url)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(sql)
        conn.close()
        return True
    except Exception as e:
        print(f"  psycopg2 error: {e}")
        return False


def main() -> None:
    prompts, version = _load_prompts()
    print(f"Found {len(prompts)} prompts (version {version}) in prompts.json")

    # Generate SQL
    sql = _generate_sql(prompts)

    # Save SQL file (always — useful for Supabase users)
    SEED_SQL_FILE.write_text(sql, encoding="utf-8")
    print(f"Saved SQL to {SEED_SQL_FILE}")

    # Try to execute
    env = _read_env(BACKEND_DIR / ".env.local")
    db_backend = env.get("DB_BACKEND", "supabase")
    executed = False

    if db_backend == "postgres":
        database_url = env.get("DATABASE_URL", "")
        if database_url:
            print(f"Executing against PostgreSQL ({database_url[:40]}...)...")
            executed = _execute_via_psycopg2(database_url, sql)
            if executed:
                print("Prompts synced to PostgreSQL")
        else:
            print("DATABASE_URL not set — SQL saved but not executed")
    else:
        # Supabase: try async DB factory
        print("DB_BACKEND=supabase — attempting async execution...")
        try:
            sys.path.insert(0, str(BACKEND_DIR / "src"))
            import asyncio
            from infrastructure.persistence.db_factory import create_db, shutdown_db

            async def _run():
                db = await create_db()
                for key, prompt_data in prompts.items():
                    variables_json = json.dumps(prompt_data.get("variables", []))
                    is_default = prompt_data.get("is_default", True)
                    existing = await (
                        db.table("analysis_prompts")
                        .select("id")
                        .eq("key", key)
                        .maybe_single()
                        .execute()
                    )
                    row = {
                        "name": prompt_data["name"],
                        "category": prompt_data["category"],
                        "prompt_template": prompt_data["prompt_template"],
                        "variables": prompt_data.get("variables", []),
                        "is_default": is_default,
                        "key": key,
                        "type": "prompt",
                    }
                    if existing and existing.data:
                        await (
                            db.table("analysis_prompts")
                            .update(row)
                            .eq("key", key)
                            .execute()
                        )
                        print(f"  Updated: {key}")
                    else:
                        await (
                            db.table("analysis_prompts")
                            .insert(row)
                            .execute()
                        )
                        print(f"  Inserted: {key}")
                await shutdown_db()

            asyncio.run(_run())
            executed = True
            print("Prompts synced to Supabase")
        except Exception as e:
            print(f"  Async execution failed: {e}")
            print(f"  SQL saved to {SEED_SQL_FILE} — paste it into the Supabase SQL editor")

    if executed:
        # Only write version marker when seeding actually succeeded
        VERSION_FILE.write_text(str(version), encoding="utf-8")
        print(f"Version marker written: {VERSION_FILE} = {version}")
    else:
        print(f"\nSQL was NOT executed. To apply manually:")
        print(f"  - Postgres: psql -U postgres -d archie -f {SEED_SQL_FILE}")
        print(f"  - Supabase: paste contents of {SEED_SQL_FILE} into SQL editor")
        sys.exit(1)


if __name__ == "__main__":
    main()
