"""Tests for the CLAUDE.md / AGENTS.md merge-preserve behavior in renderer.py.

Historically `renderer.py` overwrote these files unconditionally, clobbering
hand-authored content. The new behavior brackets generated content in HTML
comment markers and preserves anything outside them across regenerations.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest


_STANDALONE = Path(__file__).resolve().parent.parent / "archie" / "standalone"
sys.path.insert(0, str(_STANDALONE))

from renderer import (  # noqa: E402
    ARCHIE_MARKER_END,
    ARCHIE_MARKER_START,
    _append_block,
    _replace_marked_block,
    _wrap_with_markers,
    render_mergeable,
)


# ---------------------------------------------------------------------------
# _wrap_with_markers
# ---------------------------------------------------------------------------


def test_wrap_with_markers_brackets_content():
    out = _wrap_with_markers("# some content")
    assert out.startswith(ARCHIE_MARKER_START)
    assert out.rstrip().endswith(ARCHIE_MARKER_END)
    assert "# some content" in out


def test_wrap_with_markers_includes_provenance_stamp():
    """User-facing hint that Archie may rewrite between the markers."""
    out = _wrap_with_markers("body")
    assert "Regenerated by Archie" in out
    # ISO8601 date fragment (YYYY-MM-DD)
    import re

    assert re.search(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}Z", out)


# ---------------------------------------------------------------------------
# _replace_marked_block
# ---------------------------------------------------------------------------


def test_replace_marked_block_preserves_content_outside_markers():
    existing = (
        "# My notes\n\n"
        f"{ARCHIE_MARKER_START}\n"
        "old generated\n"
        f"{ARCHIE_MARKER_END}\n"
        "\n## Footer\n"
    )
    new_block = _wrap_with_markers("new generated")
    out = _replace_marked_block(existing, new_block)
    assert "# My notes" in out
    assert "## Footer" in out
    assert "old generated" not in out
    assert "new generated" in out


def test_replace_marked_block_falls_back_to_append_on_malformed_markers():
    """End marker before start marker → treated as append to avoid corruption."""
    existing = f"{ARCHIE_MARKER_END}\nweird\n{ARCHIE_MARKER_START}\nthing\n"
    new_block = _wrap_with_markers("new")
    out = _replace_marked_block(existing, new_block)
    # Original (malformed) content is preserved; new block appended
    assert existing.rstrip() in out
    assert "new" in out


# ---------------------------------------------------------------------------
# _append_block
# ---------------------------------------------------------------------------


def test_append_block_adds_separator_blank_line():
    existing = "user content\n"
    new_block = "ARCHIE\n"
    out = _append_block(existing, new_block)
    assert out == "user content\n\nARCHIE\n"


def test_append_block_handles_missing_trailing_newline():
    existing = "user content"  # no trailing newline
    new_block = "ARCHIE\n"
    out = _append_block(existing, new_block)
    assert out == "user content\n\nARCHIE\n"


# ---------------------------------------------------------------------------
# render_mergeable — the composite function used by main()
# ---------------------------------------------------------------------------


def test_render_mergeable_new_file_wraps_fresh(tmp_path):
    target = tmp_path / "CLAUDE.md"
    out = render_mergeable(target, "# Content from blueprint")
    assert ARCHIE_MARKER_START in out
    assert ARCHIE_MARKER_END in out
    assert "# Content from blueprint" in out
    # Exactly one Archie block
    assert out.count(ARCHIE_MARKER_START) == 1


def test_render_mergeable_existing_with_markers_replaces_only_block(tmp_path):
    target = tmp_path / "AGENTS.md"
    target.write_text(
        "# Project Notes\n\n"
        "Run tests: pytest -v\n\n"
        f"{ARCHIE_MARKER_START}\n"
        "STALE generated content\n"
        f"{ARCHIE_MARKER_END}\n"
        "\n## My footer\n"
    )
    out = render_mergeable(target, "FRESH blueprint-generated content")
    assert "# Project Notes" in out, "top user content lost"
    assert "Run tests: pytest -v" in out, "middle user content lost"
    assert "## My footer" in out, "bottom user content lost"
    assert "STALE generated content" not in out, "stale block not replaced"
    assert "FRESH blueprint-generated content" in out, "fresh content missing"


def test_render_mergeable_existing_without_markers_appends_block(tmp_path):
    """The critical case — user has a hand-curated file, Archie regenerates."""
    target = tmp_path / "AGENTS.md"
    user_content = (
        "# Acme Project — Agent Guide\n\n"
        "## Testing\n"
        "- Backend: `pytest tests/`\n"
        "- Frontend: `bun test`\n\n"
        "## Billing rules\n"
        "See docs/billing.md — all credit deductions go through the audit trail.\n"
    )
    target.write_text(user_content)

    out = render_mergeable(target, "# Archie blueprint summary here")

    # Every line of user content survives, byte-for-byte
    for line in user_content.strip().splitlines():
        assert line in out, f"user line lost: {line!r}"

    # User content appears BEFORE the Archie block
    assert out.index("Acme Project") < out.index(ARCHIE_MARKER_START)
    # Archie block is properly wrapped
    assert ARCHIE_MARKER_START in out
    assert ARCHIE_MARKER_END in out
    assert "# Archie blueprint summary here" in out


def test_render_mergeable_idempotent_across_multiple_regens(tmp_path):
    """Regenerating N times doesn't duplicate or nest the Archie block."""
    target = tmp_path / "CLAUDE.md"
    target.write_text("# User preamble\n\nProject details.\n")

    # First regen — file has no markers; appends
    target.write_text(render_mergeable(target, "v1 generated"))
    assert target.read_text().count(ARCHIE_MARKER_START) == 1
    assert "User preamble" in target.read_text()
    assert "v1 generated" in target.read_text()

    # Second regen — file has markers; replaces
    target.write_text(render_mergeable(target, "v2 generated"))
    text = target.read_text()
    assert text.count(ARCHIE_MARKER_START) == 1, "markers duplicated"
    assert "v1 generated" not in text, "v1 content leaked"
    assert "v2 generated" in text
    assert "User preamble" in text, "user content lost on second regen"

    # Third regen — stable
    target.write_text(render_mergeable(target, "v3 generated"))
    text = target.read_text()
    assert text.count(ARCHIE_MARKER_START) == 1
    assert "v3 generated" in text
    assert "User preamble" in text


def test_render_mergeable_preserves_user_edits_outside_markers(tmp_path):
    """Key compound case: user edits OUTSIDE markers between regens; Archie doesn't clobber."""
    target = tmp_path / "AGENTS.md"
    target.write_text("# Original user content\n")

    # Round 1: first-time collision, appends
    target.write_text(render_mergeable(target, "v1 archie"))

    # User adds new content at the TOP of the file (before the Archie block)
    current = target.read_text()
    with_user_edit = current.replace(
        "# Original user content\n",
        "# Original user content\n\n## NEW SECTION USER ADDED\nImportant!\n",
        1,
    )
    target.write_text(with_user_edit)

    # Round 2: Archie regens with v2 content
    target.write_text(render_mergeable(target, "v2 archie"))

    text = target.read_text()
    assert "NEW SECTION USER ADDED" in text, "user's new section destroyed"
    assert "Important!" in text
    assert "v2 archie" in text
    assert "v1 archie" not in text
    assert text.count(ARCHIE_MARKER_START) == 1


def test_render_mergeable_does_not_touch_unrelated_files(tmp_path):
    """Only the target file should be modified — not a regression test but a
    sanity check that we're not accidentally writing elsewhere."""
    target = tmp_path / "CLAUDE.md"
    unrelated = tmp_path / "README.md"
    unrelated.write_text("untouched README")

    target.write_text(render_mergeable(target, "generated"))
    assert unrelated.read_text() == "untouched README"
