#!/usr/bin/env python3
"""Archie standalone renderer — generates CLAUDE.md, AGENTS.md, and rule files from blueprint.

Run: python3 renderer.py /path/to/project
Reads: .archie/blueprint.json
Writes: CLAUDE.md, AGENTS.md, .claude/rules/*.md

CLAUDE.md and AGENTS.md support hand-authored content. The renderer bracketed
its generated block with `archie:generated:start` / `archie:generated:end`
HTML comment markers. On regenerate, only the bracketed block is rewritten —
content outside the markers is preserved. First-time regeneration against a
hand-authored file appends the generated block at the end so the user's
original content survives.

Zero dependencies beyond Python 3.9+ stdlib.
"""
from __future__ import annotations

import ast
import json
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Merge markers for user-editable files (CLAUDE.md / AGENTS.md)
# ---------------------------------------------------------------------------

ARCHIE_MARKER_START = "<!-- archie:generated:start -->"
ARCHIE_MARKER_END = "<!-- archie:generated:end -->"


# ---------------------------------------------------------------------------
# Comprehensive-depth render switch
# ---------------------------------------------------------------------------
#
# Default depth trims several blueprint sections to a fixed cap so the rendered
# CLAUDE.md / AGENTS.md stay lean. Comprehensive depth (the `--comprehensive`
# CLI flag, set in main()) lifts those caps so every blueprint item renders.
# Implemented as a module-level switch read by `_cap` rather than a parameter
# threaded through every render function — the slice sites are scattered across
# several builders, and a flag keeps the change small and localized.

_COMPREHENSIVE = False


def _cap(seq, n):
    """Return `seq` trimmed to `n` in default depth; the full `seq` when the
    comprehensive switch is on."""
    return seq if _COMPREHENSIVE else seq[:n]

# Files that may coexist with hand-authored content. Everything else the
# renderer emits (rule files under .claude/rules/, CLAUDE.md pointer) is
# fully Archie-owned — those still get a straight overwrite because the
# user doesn't edit them.
#
# AGENTS.md is canonical (vendor-neutral standard read by Cursor, Codex,
# Aider, Continue, Cline, Cody, and Claude Code itself). CLAUDE.md is a
# thin pointer to AGENTS.md — full-overwrite, never mergeable, so it can
# never drift from the source of truth. Per-folder context still uses
# CLAUDE.md (intent_layer.py) since nested context is dominantly a Claude
# Code idiom and other tools rarely act on it.
MERGEABLE_FILES = frozenset({"AGENTS.md"})


def _wrap_with_markers(content: str) -> str:
    """Wrap generated content in Archie markers with a provenance stamp."""
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    provenance = f"<!-- Regenerated by Archie on {stamp}. Edits between the archie:generated markers will be overwritten; edit outside them to keep changes. -->"
    return f"{ARCHIE_MARKER_START}\n{provenance}\n\n{content.rstrip()}\n{ARCHIE_MARKER_END}\n"


def _replace_marked_block(existing: str, new_block: str) -> str:
    """Replace the content between Archie markers in `existing` with `new_block`.

    Preserves every byte of `existing` outside the markers. If the end marker
    appears before the start marker (malformed), falls back to append mode
    rather than corrupting the file.
    """
    start_idx = existing.find(ARCHIE_MARKER_START)
    end_idx = existing.find(ARCHIE_MARKER_END, start_idx + len(ARCHIE_MARKER_START))
    if start_idx < 0 or end_idx < 0:
        return _append_block(existing, new_block)
    end_idx_inclusive = end_idx + len(ARCHIE_MARKER_END)
    return existing[:start_idx] + new_block.rstrip() + existing[end_idx_inclusive:]


def _append_block(existing: str, new_block: str) -> str:
    """Append `new_block` after `existing` with a clean blank line separator."""
    sep = "" if existing.endswith("\n") else "\n"
    return existing + sep + "\n" + new_block


def render_mergeable(path: Path, generated_content: str) -> str:
    """Compute the final content to write for CLAUDE.md / AGENTS.md.

    Three cases:
    - Path does not exist → return a fresh wrapped block.
    - Path exists AND contains Archie markers → replace only the bracketed block.
    - Path exists AND has no markers → append the wrapped block at the end,
      preserving the user's hand-authored content untouched.
    """
    wrapped = _wrap_with_markers(generated_content)
    if not path.exists():
        return wrapped
    existing = path.read_text()
    if ARCHIE_MARKER_START in existing and ARCHIE_MARKER_END in existing:
        return _replace_marked_block(existing, wrapped)
    return _append_block(existing, wrapped)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _clean_str_item(item) -> str:
    """Convert any item (str, dict, etc.) to readable text."""
    if isinstance(item, dict):
        # Agent returned a dict — extract meaningful fields
        parts = []
        for k, v in item.items():
            if isinstance(v, list):
                parts.append(f"{k}: {', '.join(str(x) for x in v)}")
            elif v:
                parts.append(f"{k}: {v}")
        return "; ".join(parts) if parts else str(item)
    s = str(item)
    stripped = s.strip()
    if not (stripped.startswith("{") and stripped.endswith("}")):
        return s
    try:
        obj = ast.literal_eval(stripped)
    except (ValueError, SyntaxError):
        return s
    if not isinstance(obj, dict):
        return s
    parts = []
    for k, v in obj.items():
        if isinstance(v, list):
            parts.append(f"{k}: {', '.join(str(x) for x in v)}")
        elif v:
            parts.append(f"{k}: {v}")
    return "; ".join(parts)


def _get(obj, *keys, default=None):
    """Safely traverse nested dicts."""
    current = obj
    for k in keys:
        if isinstance(current, dict):
            current = current.get(k, default)
        else:
            return default
        if current is None:
            return default
    return current


def _as_dict(val, default=None):
    """Ensure a value is a dict. If it's a string, wrap it."""
    if isinstance(val, dict):
        return val
    if default is not None:
        return default
    return {}


def _as_list(val):
    """Ensure a value is a list."""
    if isinstance(val, list):
        return val
    if isinstance(val, str) and val:
        return [val]
    return []


def _str_list(val) -> list[str]:
    """Coerce a value to a list of non-empty strings.

    Used for fields like ``violation_signals`` and ``violation_keywords``
    where a malformed blueprint might pass a string, None, or a list
    containing non-strings. Prevents per-character bullet spam and
    silently drops non-string entries.
    """
    if isinstance(val, list):
        return [s for s in val if isinstance(s, str) and s.strip()]
    if isinstance(val, str) and val.strip():
        return [val]
    return []


def _escape_table_cell(val) -> str:
    """Escape a value for safe inclusion in a markdown table cell.

    Replaces ``|`` with ``\\|`` and newlines with spaces so a malformed
    field doesn't shred the table layout. Coerces non-strings via ``str()``.
    """
    if val is None:
        return ""
    if not isinstance(val, str):
        val = str(val)
    return val.replace("|", r"\|").replace("\n", " ").strip()


# ---------------------------------------------------------------------------
# Frontend glob detection
# ---------------------------------------------------------------------------

_FRONTEND_GLOB_MAP = {
    "react": ["**/*.tsx", "**/*.jsx"],
    "next": ["**/*.tsx", "**/*.jsx"],
    "vue": ["**/*.vue"],
    "svelte": ["**/*.svelte"],
    "angular": ["**/*.ts", "**/*.html"],
    "flutter": ["**/*.dart"],
    "swiftui": ["**/*.swift"],
    "swift": ["**/*.swift"],
    "kotlin": ["**/*.kt"],
    "react native": ["**/*.tsx", "**/*.jsx"],
}


def _detect_frontend_globs(bp: dict) -> list:
    """Return frontend-specific globs based on framework and tech stack."""
    globs = set()
    fw = (_get(bp, "frontend", "framework", default="") or "").lower()
    for key, patterns in _FRONTEND_GLOB_MAP.items():
        if key in fw:
            globs.update(patterns)
    for entry in _get(bp, "technology", "stack", default=[]) or []:
        name_lower = (entry.get("name", "") or "").lower()
        for key, patterns in _FRONTEND_GLOB_MAP.items():
            if key in name_lower:
                globs.update(patterns)
    return sorted(globs) if globs else ["**/*"]


# ---------------------------------------------------------------------------
# Rule file builders (mirror agent_file_generator.py exactly)
# ---------------------------------------------------------------------------

def _build_architecture_rule(bp: dict):
    """Components, file placement, naming, where-to-put."""
    lines = []

    # Components
    components = _get(bp, "components", "components", default=[]) or []
    if components:
        lines.append("## Components")
        lines.append("")
        for comp in components:
            lines.append(f"### {comp.get('name', '')}")
            lines.append(f"- **Location:** `{comp.get('location', '')}`")
            lines.append(f"- **Responsibility:** {comp.get('responsibility', '')}")
            deps = comp.get("depends_on") or []
            if deps:
                lines.append(f"- **Depends on:** {', '.join(deps)}")
            key_ifaces = comp.get("key_interfaces") or []
            if key_ifaces:
                if isinstance(key_ifaces[0], dict):
                    iface_strs = []
                    for iface in key_ifaces:
                        name = iface.get("name", "")
                        methods = iface.get("methods") or []
                        if methods:
                            iface_strs.append(f"`{name}` ({', '.join(methods)})")
                        else:
                            iface_strs.append(f"`{name}`")
                    lines.append(f"- **Key interfaces:** {', '.join(iface_strs)}")
                elif isinstance(key_ifaces[0], str):
                    lines.append(f"- **Key interfaces:** {', '.join(f'`{i}`' for i in key_ifaces)}")
                else:
                    print(f"Warning: unexpected {type(key_ifaces[0]).__name__} in key_interfaces, coercing", file=sys.stderr)
                    lines.append(f"- **Key interfaces:** {', '.join(f'`{str(i)}`' for i in key_ifaces)}")
            lines.append("")

    # File Placement
    fp_rules = _get(bp, "architecture_rules", "file_placement_rules", default=[]) or []
    if fp_rules:
        lines.append("## File Placement")
        lines.append("")
        lines.append("| Component Type | Location | Naming | Example |")
        lines.append("|---------------|----------|--------|---------|")
        for fp in fp_rules:
            lines.append(
                f"| {fp.get('component_type', '')} | `{fp.get('location', '')}` | `{fp.get('naming_pattern', '')}` | `{fp.get('example', '')}` |"
            )
        lines.append("")

    # Where to Put Code
    where = _get(bp, "quick_reference", "where_to_put_code", default={}) or {}
    if where:
        lines.append("## Where to Put Code")
        lines.append("")
        for comp_type, loc in where.items():
            lines.append(f"- **{comp_type}** -> `{loc}`")
        lines.append("")

    # Naming Conventions
    naming = _get(bp, "architecture_rules", "naming_conventions", default=[]) or []
    if naming:
        lines.append("## Naming Conventions")
        lines.append("")
        for nc in naming:
            examples = ", ".join(f"`{e}`" for e in _cap(nc.get("examples") or [], 4))
            lines.append(f"- **{nc.get('scope', '')}**: {nc.get('pattern', '')} (e.g. {examples})")
        lines.append("")

    if not lines:
        return None

    return {
        "topic": "architecture",
        "body": "\n".join(lines).rstrip(),
        "description": "Architecture rules: components, file placement, naming conventions",
        "always_apply": True,
        "globs": [],
    }


def _render_communication_pattern_block(pat: dict) -> list[str]:
    """Render one communication.patterns entry as markdown lines."""
    lines: list[str] = [f"### {pat.get('name', '')}"]
    scope = _str_list(pat.get("scope"))
    if scope:
        lines.append(f"- **Scope:** {', '.join(f'`{s}`' for s in scope)}")
    lines.append(f"- **When:** {pat.get('when_to_use', '')}")
    lines.append(f"- **How:** {pat.get('how_it_works', '')}")
    if pat.get("applicable_when"):
        lines.append(f"- **Applicable when:** {pat['applicable_when']}")
    do_not = _str_list(pat.get("do_not_apply_when"))
    if do_not:
        lines.append("- **Do NOT apply when:**")
        for item in do_not:
            lines.append(f"  - {item}")
    lines.append("")
    return lines


def _build_patterns_rule(bp: dict):
    """Communication patterns, pattern selection, decisions.

    Single repo-wide ``patterns.md`` rule file. Each pattern entry renders
    its ``scope``, ``applicable_when``, and ``do_not_apply_when`` inline so
    a coding agent reading the rule sees the boundary conditions explicitly.
    The file is always loaded; agents are expected to read the inline
    Scope/Applicable-when/Do-NOT-apply-when lines and self-filter.
    """
    lines = []

    # Communication Patterns
    raw_patterns = _get(bp, "communication", "patterns", default=[]) or []
    valid_patterns = [p for p in raw_patterns if isinstance(p, dict)]
    if valid_patterns:
        lines.append("## Communication Patterns")
        lines.append("")
        for pat in valid_patterns:
            lines.extend(_render_communication_pattern_block(pat))

    # Integrations — external services and their architectural entry points.
    # Critical for agents editing code that touches ingestion, billing, search,
    # etc., so they know which seam owns the integration.
    integrations = _get(bp, "communication", "integrations", default=[]) or []
    valid_integrations = [ig for ig in integrations if isinstance(ig, dict)]
    if valid_integrations:
        lines.append("## Integrations")
        lines.append("")
        lines.append("| Service | Purpose | Integration point |")
        lines.append("|---------|---------|-------------------|")
        for ig in valid_integrations:
            service = _escape_table_cell(ig.get("service") or ig.get("name", ""))
            purpose = _escape_table_cell(ig.get("purpose", ""))
            point = ig.get("integration_point", "") or ""
            if not isinstance(point, str):
                point = str(point)
            # Preserve backticks around file paths when present.
            point_fmt = f"`{point}`" if point and "/" in point and "`" not in point else point
            lines.append(f"| {service} | {purpose} | {_escape_table_cell(point_fmt)} |")
        lines.append("")

    # Pattern Selection Guide
    psg_list = _get(bp, "communication", "pattern_selection_guide", default=[]) or []
    if psg_list:
        lines.append("## Pattern Selection Guide")
        lines.append("")
        lines.append("| Scenario | Pattern | Rationale |")
        lines.append("|----------|---------|-----------|")
        for psg in psg_list:
            lines.append(f"| {psg.get('scenario', '')} | {psg.get('pattern', '')} | {psg.get('rationale', '')} |")
        lines.append("")

    # Quick Reference: Pattern Selection. Two shapes supported:
    #   legacy: dict {scenario: pattern}
    #   new:    list [{scenario, pattern, scope}]
    # Each entry renders ``scope`` inline when present so an agent reading
    # the lookup table sees which components the entry applies to.
    ps = _get(bp, "quick_reference", "pattern_selection", default=None)
    quickref_lines: list[str] = []
    if isinstance(ps, dict) and ps:
        for scenario, pattern in ps.items():
            quickref_lines.append(f"- **{scenario}** -> {pattern}")
    elif isinstance(ps, list) and ps:
        for entry in ps:
            if not isinstance(entry, dict):
                continue
            scenario = entry.get("scenario", "")
            pattern = entry.get("pattern", "")
            if not scenario or not pattern:
                continue
            entry_scope = _str_list(entry.get("scope"))
            line = f"- **{scenario}** -> {pattern}"
            if entry_scope:
                line += f"  *(scope: {', '.join(entry_scope)})*"
            quickref_lines.append(line)
    if quickref_lines:
        lines.append("## Quick Pattern Lookup")
        lines.append("")
        lines.extend(quickref_lines)
        lines.append("")

    # Decision Chain — the rooted forces tree, rendered with
    # violation_keywords under each force. These are the concrete code-
    # pattern fingerprints that would breach a decision; surfacing them
    # next to the "why" is the whole point of the chain.
    decision_chain = _get(bp, "decisions", "decision_chain", default={}) or {}
    if decision_chain.get("root"):
        lines.append("## Decision Chain")
        lines.append("")
        lines.append(f"**Root constraint:** {decision_chain['root']}")
        lines.append("")

        def _render_chain(forces, indent=0):
            for f in (forces or []):
                if not isinstance(f, dict):
                    continue
                prefix = "  " * indent + "- "
                lines.append(f"{prefix}**{f.get('decision', '')}**: {f.get('rationale', '')}")
                for kw in _str_list(f.get("violation_keywords")):
                    lines.append(f"{'  ' * (indent + 1)}- *Violation keyword:* `{kw}`")
                _render_chain(f.get("forces", []), indent + 1)

        _render_chain(decision_chain.get("forces", []))
        lines.append("")

    # Key Decisions
    key_decs = _get(bp, "decisions", "key_decisions", default=[]) or []
    if key_decs:
        lines.append("## Key Decisions")
        lines.append("")
        for dec in key_decs:
            lines.append(f"### {dec.get('title', '')}")
            lines.append(f"**Chosen:** {dec.get('chosen', '')}")
            rationale = dec.get("rationale", "")
            if rationale:
                lines.append(f"**Rationale:** {rationale}")
            alternatives = dec.get("alternatives_rejected") or []
            if alternatives:
                lines.append(f"**Rejected:** {', '.join(alternatives)}")
            forced_by = dec.get("forced_by", "")
            if forced_by:
                lines.append(f"**Forced by:** {forced_by}")
            enables = dec.get("enables", "")
            if enables:
                lines.append(f"**Enables:** {enables}")
            lines.append("")

    # Trade-offs — rendered as a list (not a table) so violation_signals can
    # be surfaced as sub-bullets. violation_signals is the most enforcement-
    # relevant field: it enumerates code-level patterns that would undo the
    # trade-off, which is exactly what agents need to recognise before writing.
    trade_offs = _get(bp, "decisions", "trade_offs", default=[]) or []
    valid_trade_offs = [to for to in trade_offs if isinstance(to, dict)]
    if valid_trade_offs:
        lines.append("## Trade-offs Accepted")
        lines.append("")
        for to in valid_trade_offs:
            accept = to.get("accept", "") or to.get("accepted", "")
            benefit = to.get("benefit", "") or to.get("gained", "")
            caused_by = to.get("caused_by", "")
            lines.append(f"- **Accepted:** {accept}")
            if benefit:
                lines.append(f"  - *Benefit:* {benefit}")
            if caused_by:
                lines.append(f"  - *Caused by:* {caused_by}")
            for sig in _str_list(to.get("violation_signals")):
                lines.append(f"  - *Violation signal:* {sig}")
        lines.append("")

    # Out of Scope
    out_of_scope = _get(bp, "decisions", "out_of_scope", default=[]) or []
    if out_of_scope:
        lines.append("## Out of Scope")
        lines.append("")
        for item in out_of_scope:
            lines.append(f"- {item}")
        lines.append("")

    if not lines:
        return None

    return {
        "topic": "patterns",
        "body": "\n".join(lines).rstrip(),
        "description": "Communication and design patterns, key architectural decisions",
        "always_apply": True,
        "globs": [],
    }


def _build_frontend_rule(bp: dict):
    """Frontend architecture rules."""
    fe = _as_dict(bp.get("frontend"))
    has_frontend = fe.get("framework") or fe.get("ui_components") or fe.get("routing") or fe.get("data_fetching")
    if not has_frontend:
        return None

    lines = []
    lines.append("## Frontend Architecture")
    lines.append("")

    if fe.get("framework"):
        lines.append(f"**Framework:** {fe['framework']}")
        lines.append("")
    if fe.get("rendering_strategy"):
        lines.append(f"**Rendering:** {fe['rendering_strategy']}")
        lines.append("")
    if fe.get("styling"):
        lines.append(f"**Styling:** {fe['styling']}")
        lines.append("")

    sm = fe.get("state_management") or {}
    if isinstance(sm, str):
        lines.append(f"**State management:** {sm}")
        lines.append("")
    elif isinstance(sm, dict) and sm.get("approach"):
        lines.append(f"**State management:** {sm['approach']}")
        if sm.get("server_state"):
            lines.append(f"  - Server state: {sm['server_state']}")
        if sm.get("local_state"):
            lines.append(f"  - Local state: {sm['local_state']}")
        lines.append("")

    if fe.get("key_conventions"):
        lines.append("**Conventions:**")
        for conv in fe["key_conventions"]:
            lines.append(f"- {conv}")
        lines.append("")

    globs = _detect_frontend_globs(bp)

    return {
        "topic": "frontend",
        "body": "\n".join(lines).rstrip(),
        "description": "Frontend architecture rules",
        "always_apply": False,
        "globs": globs,
    }


def _render_guideline_block(gl: dict) -> list[str]:
    """Render one implementation_guidelines entry as markdown lines."""
    lines: list[str] = []
    cat_tag = f" [{gl['category']}]" if gl.get("category") else ""
    lines.append(f"### {gl['capability']}{cat_tag}")
    scope = _str_list(gl.get("scope"))
    if scope:
        lines.append(f"**Scope:** {', '.join(f'`{s}`' for s in scope)}")
    libs = gl.get("libraries") or []
    if libs:
        lines.append(f"Libraries: {', '.join(f'`{lib}`' for lib in libs)}")
    if gl.get("pattern_description"):
        lines.append(f"Pattern: {gl['pattern_description']}")
    key_files = gl.get("key_files") or []
    if key_files:
        lines.append(f"Key files: {', '.join(f'`{f}`' for f in key_files)}")
    if gl.get("usage_example"):
        lines.append(f"Example: `{gl['usage_example']}`")
    if gl.get("applicable_when"):
        lines.append(f"**Applicable when:** {gl['applicable_when']}")
    do_not = _str_list(gl.get("do_not_apply_when"))
    if do_not:
        lines.append("**Do NOT apply when:**")
        for item in do_not:
            lines.append(f"  - {item}")
    tips = gl.get("tips") or []
    if tips:
        for tip in tips:
            lines.append(f"- {tip}")
    lines.append("")
    return lines


def _build_guidelines_rule(bp: dict):
    """Implementation guidelines.

    Single repo-wide ``guidelines.md`` rule file. Each guideline renders its
    ``scope``, ``applicable_when``, and ``do_not_apply_when`` inline so a
    coding agent reading the rule sees the boundary conditions explicitly.
    """
    guidelines = bp.get("implementation_guidelines") or []
    if not guidelines:
        return None

    body_lines: list[str] = ["## Implementation Guidelines", ""]
    rendered = False
    for gl in guidelines:
        if not gl.get("capability"):
            continue
        body_lines.extend(_render_guideline_block(gl))
        rendered = True

    if not rendered:
        return None

    return {
        "topic": "guidelines",
        "body": "\n".join(body_lines).rstrip(),
        "description": "Implementation guidelines for existing capabilities",
        "always_apply": True,
        "globs": [],
    }


def _render_pitfall_lines(pitfall: dict) -> list[str]:
    """Render one pitfall as markdown. Accepts the 4-field shape
    (problem_statement/evidence/root_cause/fix_direction) or the legacy
    shape (area/description/recommendation/stems_from) for backward
    compatibility with blueprints written before 2.3.0.
    """
    # New 4-field shape
    if pitfall.get("problem_statement"):
        lines = [f"- **{pitfall['problem_statement']}**"]
        evidence = pitfall.get("evidence") or []
        if evidence:
            ev_preview = "; ".join(str(e) for e in _cap(evidence, 3))
            if len(evidence) > 3:
                ev_preview += f"; … ({len(evidence)} total)"
            lines.append(f"  - *Evidence:* {ev_preview}")
        if pitfall.get("root_cause"):
            lines.append(f"  - *Root cause:* {pitfall['root_cause']}")
        fix = pitfall.get("fix_direction")
        if isinstance(fix, list) and fix:
            lines.append(f"  - *Fix direction:*")
            for step in fix:
                lines.append(f"    - {step}")
        elif isinstance(fix, str) and fix:
            lines.append(f"  - *Fix direction:* {fix}")
        return lines

    # Legacy shape
    if pitfall.get("area") or pitfall.get("description"):
        area_label = f"**{pitfall['area']}:** " if pitfall.get("area") else ""
        lines = [f"- {area_label}{pitfall.get('description', '')}"]
        if pitfall.get("recommendation"):
            lines.append(f"  - *{pitfall['recommendation']}*")
        return lines

    return []


def _build_pitfalls_rule(bp: dict):
    """Pitfalls + error mapping."""
    lines = []

    pitfalls = bp.get("pitfalls") or []
    if pitfalls:
        lines.append("## Pitfalls")
        lines.append("")
        for pitfall in pitfalls:
            rendered = _render_pitfall_lines(pitfall)
            lines.extend(rendered)
        lines.append("")

    # Error Mapping
    error_mapping = _get(bp, "quick_reference", "error_mapping", default=[]) or []
    if error_mapping:
        lines.append("## Error Mapping")
        lines.append("")
        lines.append("| Error | Status Code |")
        lines.append("|-------|------------|")
        for em in error_mapping:
            lines.append(f"| `{em.get('error', '')}` | {em.get('status_code', '')} |")
        lines.append("")

    if not lines:
        return None

    return {
        "topic": "pitfalls",
        "body": "\n".join(lines).rstrip(),
        "description": "Common pitfalls and error mapping",
        "always_apply": True,
        "globs": [],
    }


def _render_grouped_rules(rules: list, heading: str) -> list[str]:
    """Render a grouped-by-category list of imperative rules. Shared helper
    used by both development_rules and infrastructure_rules renderers."""
    if not rules:
        return []
    by_category = defaultdict(list)
    for dr in rules:
        cat = (dr.get("category") or "").strip() or "general"
        by_category[cat].append(dr)
    out = [f"## {heading}", ""]
    for cat_name in sorted(by_category.keys()):
        sub = cat_name.replace("_", " ").title()
        out.append(f"### {sub}")
        out.append("")
        for dr in by_category[cat_name]:
            if dr.get("source"):
                out.append(f"- {dr.get('rule', '')} *(source: `{dr['source']}`)*")
            else:
                out.append(f"- {dr.get('rule', '')}")
        out.append("")
    return out


def _build_dev_rules_rule(bp: dict):
    """Development rules — coding-time rules a coding agent consults
    when writing or refactoring code. Infrastructure rules live in
    their own topic file (`infrastructure.md`) so this surface stays
    focused on what the agent reads at edit time."""
    dev_rules = bp.get("development_rules") or []
    if not dev_rules:
        return None

    lines = _render_grouped_rules(dev_rules, "Development Rules")

    return {
        "topic": "dev-rules",
        "body": "\n".join(lines).rstrip(),
        "description": "Development rules: imperative do/don't rules from codebase signals",
        "always_apply": True,
        "globs": [],
    }


def _build_infrastructure_rule(bp: dict):
    """Infrastructure rules — CI / signing / distribution / secrets / env_setup
    / dependency_registry / git. Onboarding-time and pipeline-touching info,
    deliberately separate from `dev-rules.md` so coding agents don't wade
    through CI YAML noise when looking for coding patterns."""
    infra_rules = bp.get("infrastructure_rules") or []
    if not infra_rules:
        return None
    lines = _render_grouped_rules(infra_rules, "Infrastructure Rules")
    return {
        "topic": "infrastructure",
        "body": "\n".join(lines).rstrip(),
        "description": "Infrastructure rules: CI, signing, distribution, secrets, env setup, registry auth",
        "always_apply": False,
        "globs": [],
    }


_STORE_ROLE_PRIORITY = {
    "primary": 0,
    "search": 1,
    "queue": 2,
    "cache": 3,
    "local": 4,
    "analytics": 5,
    "object_storage": 6,
}


def _data_model_weight(m: dict) -> tuple[int, int, str]:
    """Sort key for data_models — most-referenced first (consumers count
    desc, then field count desc, then name asc). Negated counts so that
    descending order falls out of a default-ascending sort.

    Falls back to legacy `key_fields` when a pre-v2 blueprint hasn't been
    rescanned yet, so old blueprints still order sensibly under the new
    UI.
    """
    if not isinstance(m, dict):
        return (0, 0, "")
    consumers = m.get("consumers")
    if isinstance(consumers, list):
        c_count = len(consumers)
    else:
        legacy = (m.get("lifecycle") or {}).get("related_business_logic") or []
        c_count = len(legacy) if isinstance(legacy, list) else 0
    fields = m.get("fields")
    if isinstance(fields, list) and fields:
        f_count = len(fields)
    else:
        kf = m.get("key_fields") or []
        f_count = len(kf) if isinstance(kf, list) else 0
    return (-c_count, -f_count, str(m.get("name", "")))


def _persistence_store_weight(s: dict) -> tuple[int, int, str]:
    """Sort key for persistence_stores — most-data first (owned model count
    desc, then role priority asc, then name asc)."""
    if not isinstance(s, dict):
        return (0, 99, "")
    owned = s.get("owned_models") or []
    owned_count = len(owned) if isinstance(owned, list) else 0
    role = (s.get("role") or "").strip().lower()
    role_rank = _STORE_ROLE_PRIORITY.get(role, 99)
    return (-owned_count, role_rank, str(s.get("name", "")))


def _sort_data_models(models: list) -> list:
    """Return data_models sorted by importance (see `_data_model_weight`)."""
    return sorted([m for m in models if isinstance(m, dict)], key=_data_model_weight)


def _sort_persistence_stores(stores: list) -> list:
    """Return persistence_stores sorted by importance (see
    `_persistence_store_weight`)."""
    return sorted([s for s in stores if isinstance(s, dict)], key=_persistence_store_weight)


_DATA_MODELS_SECTION_INTRO = (
    "Domain entities, DTOs, and value objects this codebase reads and writes."
)
_PERSISTENCE_STORES_SECTION_INTRO = (
    "Where data lives across process or session boundaries — databases, "
    "caches, queues, mobile local storage."
)


def _normalize_data_model_fields(m: dict) -> list[dict]:
    """Coerce a data_model's field list to the new {name, type, description}
    shape. Accepts both the new shape and the legacy `key_fields: ["id", ...]`
    string array for blueprints produced before the schema upgrade."""
    fields = m.get("fields")
    if isinstance(fields, list) and fields:
        out: list[dict] = []
        for f in fields:
            if isinstance(f, dict):
                out.append({
                    "name": str(f.get("name", "")),
                    "type": str(f.get("type", "")),
                    "description": str(f.get("description", "")),
                })
            elif isinstance(f, str):
                out.append({"name": f, "type": "", "description": ""})
        return out
    # Legacy fallback: key_fields was a string list.
    legacy = m.get("key_fields") or []
    if isinstance(legacy, list):
        return [
            {"name": str(k), "type": "", "description": ""}
            for k in legacy if isinstance(k, (str, int))
        ]
    return []


def _normalize_data_model_guarantees(m: dict) -> list[str]:
    """Return the guarantees array. Accepts new `guarantees` key, falls back
    to legacy `invariants`."""
    g = m.get("guarantees")
    if isinstance(g, list):
        return [str(x) for x in g if isinstance(x, (str, int))]
    legacy = m.get("invariants")
    if isinstance(legacy, list):
        return [str(x) for x in legacy if isinstance(x, (str, int))]
    return []


def _normalize_data_model_consumers(m: dict) -> list[dict]:
    """Return consumers in the new {object, file, role} shape. Falls back to
    legacy `lifecycle.related_business_logic: ["path/to/file.py"]` by mapping
    each path to a consumer with empty object/role."""
    c = m.get("consumers")
    if isinstance(c, list) and c:
        out: list[dict] = []
        for item in c:
            if isinstance(item, dict):
                out.append({
                    "object": str(item.get("object", "")),
                    "file": str(item.get("file", "")),
                    "role": str(item.get("role", "")),
                })
            elif isinstance(item, str):
                out.append({"object": "", "file": item, "role": ""})
        return out
    lifecycle = m.get("lifecycle") or {}
    if isinstance(lifecycle, dict):
        legacy = lifecycle.get("related_business_logic") or []
        if isinstance(legacy, list):
            return [
                {"object": "", "file": str(p), "role": ""}
                for p in legacy if isinstance(p, str)
            ]
    return []


def _normalize_data_model_lifecycle(m: dict) -> dict:
    """Return the lifecycle dict with how_to_* entries as {prose, example}
    objects. Accepts legacy strings (where prose was the entire value and
    no example existed) and wraps them."""
    lifecycle = m.get("lifecycle") or {}
    if not isinstance(lifecycle, dict):
        return {}
    out: dict = {}
    for key in ("how_to_add", "how_to_modify", "how_to_read"):
        raw = lifecycle.get(key)
        if isinstance(raw, dict):
            out[key] = {
                "prose": str(raw.get("prose", "")),
                "example": str(raw.get("example", "")),
            }
        elif isinstance(raw, str) and raw:
            out[key] = {"prose": raw, "example": ""}
        else:
            out[key] = {"prose": "", "example": ""}
    out["backup_strategy"] = str(lifecycle.get("backup_strategy") or "")
    tests = lifecycle.get("tests") or []
    out["tests"] = [str(t) for t in tests if isinstance(t, str)]
    return out


def _build_data_models_rule(bp: dict):
    """Persistence stores, data models, and per-model lifecycle.

    Renders the full `data_models` + `persistence_stores` blueprint sections
    so an agent touching a model has the full per-model picture (fields with
    business descriptions, data guarantees, consumers with their role, and
    lifecycle prose + code examples) without re-reading the blueprint.
    Returns None when neither section is populated — silently elides for
    repos with no persistence.

    Accepts both the new schema (fields/guarantees/consumers/lifecycle.*.example)
    and the legacy schema (key_fields/invariants/lifecycle.related_business_logic
    /lifecycle.how_to_* as strings) for blueprints produced before the upgrade.
    """
    data_models = _sort_data_models(bp.get("data_models") or [])
    persistence_stores = _sort_persistence_stores(bp.get("persistence_stores") or [])
    if not data_models and not persistence_stores:
        return None

    lines: list[str] = []

    overview = bp.get("data_overview") or ""
    if isinstance(overview, str) and overview.strip():
        lines.append(overview.strip())
        lines.append("")

    if data_models:
        lines.append("## Models")
        lines.append("")
        lines.append(f"_{_DATA_MODELS_SECTION_INTRO}_")
        lines.append("")
        for m in data_models:
            name = m.get("name", "")
            description = m.get("description") or ""
            kind = m.get("kind", "")
            location = m.get("location", "")
            store = m.get("store", "")
            owner = m.get("owned_by_component", "")
            fields = _normalize_data_model_fields(m)
            guarantees = _normalize_data_model_guarantees(m)
            consumers = _normalize_data_model_consumers(m)
            lifecycle = _normalize_data_model_lifecycle(m)

            head = f"### `{name}`"
            if kind:
                head += f" *({kind})*"
            lines.append(head)
            if description.strip():
                lines.append("")
                lines.append(description.strip())
                lines.append("")
            if location:
                lines.append(f"- **Location:** `{location}`")
            if store:
                lines.append(f"- **Store:** `{store}`")
            if owner:
                lines.append(f"- **Owner:** `{owner}`")

            if fields:
                lines.append("")
                lines.append("**Fields:**")
                lines.append("")
                lines.append("| Field | Type | Description |")
                lines.append("|---|---|---|")
                for f in fields:
                    fn = f["name"]
                    ft = f["type"] or "—"
                    fd = f["description"] or ""
                    # Escape pipes in description so the table doesn't break.
                    fd = fd.replace("|", "\\|")
                    lines.append(f"| `{fn}` | {ft} | {fd} |")
                lines.append("")

            if guarantees:
                lines.append("**Data Guarantees:**")
                for g in guarantees:
                    lines.append(f"- {g}")
                lines.append("")

            if consumers:
                lines.append("**Consumers:**")
                for c in consumers:
                    obj = c["object"]
                    fpath = c["file"]
                    role = c["role"]
                    head_str = f"- `{obj}`" if obj else "-"
                    if fpath:
                        head_str += f" — `{fpath}`" if obj else f" `{fpath}`"
                    if role:
                        head_str += f": {role}"
                    lines.append(head_str)
                lines.append("")

            lifecycle_has_content = any(
                lifecycle.get(k, {}).get("prose") or lifecycle.get(k, {}).get("example")
                for k in ("how_to_add", "how_to_modify", "how_to_read")
            ) or lifecycle.get("backup_strategy") or lifecycle.get("tests")
            if lifecycle_has_content:
                lines.append("**Lifecycle:**")
                for label, key in (
                    ("How to add", "how_to_add"),
                    ("How to modify", "how_to_modify"),
                    ("How to read", "how_to_read"),
                ):
                    entry = lifecycle.get(key) or {}
                    prose = entry.get("prose") or ""
                    example = entry.get("example") or ""
                    if not prose and not example:
                        continue
                    lines.append(f"- *{label}:* {prose}" if prose else f"- *{label}:*")
                    if example:
                        lines.append("")
                        lines.append("  ```")
                        for ex_line in example.split("\n"):
                            lines.append(f"  {ex_line}")
                        lines.append("  ```")
                        lines.append("")
                backup = lifecycle.get("backup_strategy") or ""
                if backup:
                    lines.append(f"- *Backup:* {backup}")
                tests = lifecycle.get("tests") or []
                if tests:
                    lines.append(
                        "- *Tests:* " + ", ".join(f"`{p}`" for p in tests)
                    )
            lines.append("")

    if persistence_stores:
        lines.append("## Persistence Stores")
        lines.append("")
        lines.append(f"_{_PERSISTENCE_STORES_SECTION_INTRO}_")
        lines.append("")
        for s in persistence_stores:
            name = s.get("name", "")
            description = s.get("description") or ""
            engine = s.get("engine", "")
            role = s.get("role", "")
            mig = s.get("migrations_dir", "")
            backup = s.get("backup_strategy", "")
            owned = s.get("owned_models") or []
            writers = s.get("writers") or []
            lines.append(f"### `{name}`")
            if description.strip():
                lines.append("")
                lines.append(description.strip())
                lines.append("")
            if engine:
                lines.append(f"- **Engine:** {engine}")
            if role:
                lines.append(f"- **Role:** {role}")
            if mig:
                lines.append(f"- **Migrations dir:** `{mig}`")
            if backup:
                lines.append(f"- **Backup:** {backup}")
            if owned:
                lines.append(f"- **Lives here:** {', '.join(owned)}")
            if writers:
                # Derived from data_models[*].owned_by_component during finalize
                # (see finalize.py::_derive_persistence_writers). Empty on
                # blueprints rendered before that derivation existed.
                lines.append(f"- **Written by:** {', '.join(writers)}")
            lines.append("")

    return {
        "topic": "data-models",
        "body": "\n".join(lines).rstrip(),
        "description": "Models (sorted by most-referenced) and the stores they live in, with descriptions and per-model lifecycle",
        "always_apply": False,
        "globs": [],
    }


# Keywords that mark a command as "essential" — what an agent reaches for
# in 80% of sessions. Anything not matching one of these gets pushed to
# the technology.md catalog and out of the lean root file.
_ESSENTIAL_COMMAND_KEYWORDS = (
    "build", "test", "lint", "fmt", "format", "run", "serve", "start", "dev", "up",
)
_ESSENTIAL_COMMAND_LIMIT = 8


def _essential_commands(run_commands: dict) -> dict:
    """Curate a lean subset of run_commands for the root CLAUDE.md / AGENTS.md.

    Scores each command by keyword match (build / test / lint / fmt / run /
    serve / start / dev / up) and prefers exact matches and shorter names —
    so `build` outranks `build-server` and `test` outranks `test-nocache`.
    Capped at 8 entries regardless of project size; the full catalog lives
    in `.claude/rules/technology.md`.
    """
    scored: list[tuple[tuple[bool, int], str, str]] = []
    for k, v in run_commands.items():
        kl = k.lower()
        for kw in _ESSENTIAL_COMMAND_KEYWORDS:
            if kw in kl:
                # Sort key: exact-name match wins, then shorter name wins.
                # Negative length so larger tuple = higher priority on desc sort.
                scored.append(((kl == kw, -len(k)), k, v))
                break
    scored.sort(reverse=True)
    return {k: v for _, k, v in scored[:_ESSENTIAL_COMMAND_LIMIT]}


def _build_technology_rule(bp: dict):
    """Tech stack, project structure, code templates, testing tooling.

    Surfaces what was previously only in AGENTS.md so a single topic file
    captures the project's tech footprint. Agents land here when the question
    is "what stack are we on / where does what live / how do tests run."
    """
    stack = _get(bp, "technology", "stack", default=[]) or []
    project_structure = _get(bp, "technology", "project_structure")
    templates = _get(bp, "technology", "templates", default=[]) or []
    run_commands = _get(bp, "technology", "run_commands", default={}) or {}
    test_commands = {
        k: v for k, v in run_commands.items()
        if any(t in k.lower() for t in ("test", "lint", "check", "verify"))
    }
    test_stack = [
        e for e in stack
        if (e.get("category") or "").lower() in ("testing", "linting")
    ]

    if not (stack or project_structure or templates or test_commands or test_stack):
        return None

    lines: list[str] = []

    # Tech Stack — grouped by category for fast scanning
    if stack:
        lines.append("## Tech Stack")
        lines.append("")
        by_cat = defaultdict(list)
        for entry in stack:
            version = f" {entry['version']}" if entry.get("version") else ""
            by_cat[entry.get("category", "Other")].append(f"{entry.get('name', '')}{version}")
        for cat in sorted(by_cat.keys()):
            techs = ", ".join(by_cat[cat])
            lines.append(f"- **{cat}:** {techs}")
        lines.append("")

    # Project Structure — ASCII tree (Wave-1 generated)
    if project_structure:
        lines.append("## Project Structure")
        lines.append("")
        lines.append("```")
        lines.append(project_structure)
        lines.append("```")
        lines.append("")

    # Run Commands — the FULL catalog. The lean root only surfaces the
    # essential subset (build / test / lint / fmt / run/serve/up); the
    # rest live here so agents looking for a specific make target know
    # where to find it.
    if run_commands:
        lines.append("## Run Commands")
        lines.append("")
        lines.append("```bash")
        for cmd_name, cmd_value in run_commands.items():
            lines.append(f"# {cmd_name}")
            lines.append(cmd_value)
        lines.append("```")
        lines.append("")

    # Code Templates — concrete shapes for adding new components
    if templates:
        lines.append("## Code Templates")
        lines.append("")
        for tmpl in _cap(templates, 6):
            code = tmpl.get("code")
            if not code:
                continue
            lines.append(f"### {tmpl.get('component_type', '')}: {tmpl.get('description', '')}")
            lines.append("")
            if tmpl.get("file_path_template"):
                lines.append(f"File: `{tmpl['file_path_template']}`")
                lines.append("")
            lines.append("```")
            lines.append(code)
            lines.append("```")
            lines.append("")

    # Testing
    if test_stack or test_commands:
        lines.append("## Testing")
        lines.append("")
        if test_stack:
            for entry in test_stack:
                version = f" {entry['version']}" if entry.get("version") else ""
                lines.append(f"- **{entry.get('name', '')}{version}** — {entry.get('purpose', '')}")
            lines.append("")
        if test_commands:
            lines.append("```bash")
            for cmd_name, cmd_value in test_commands.items():
                lines.append(f"# {cmd_name}")
                lines.append(cmd_value)
            lines.append("```")
            lines.append("")

    return {
        "topic": "technology",
        "body": "\n".join(lines).rstrip(),
        "description": "Tech stack, project structure, code templates, testing tooling",
        "always_apply": True,
        "globs": [],
    }


# ---------------------------------------------------------------------------
# Render rule files with platform-specific frontmatter
# ---------------------------------------------------------------------------

def _render_claude(rule: dict) -> str:
    """Render for Claude Code (.claude/rules/)."""
    globs = rule.get("globs") or []
    if globs:
        globs_yaml = "\n".join(f"  - {g}" for g in globs)
        return f"---\npaths:\n{globs_yaml}\n---\n\n{rule['body']}"
    return rule["body"]




# ---------------------------------------------------------------------------
# Canonical agent-context body (lean root file — <120 lines).
#
# This is what gets written to AGENTS.md (the canonical file on disk) and
# what the viewer renders for the CLAUDE.md tab. The H1 is parameterized
# so the same body can be branded for either filename without duplicate
# code paths.
# ---------------------------------------------------------------------------

def _generate_agent_body(bp: dict, *, h1: str) -> str:
    """Generate the lean blueprint-derived agent-context body.

    `h1` is the H1 heading (e.g. "AGENTS.md" or "CLAUDE.md"). The rest of
    the body is identical regardless of filename — same blueprint, same
    sections.
    """
    timestamp = datetime.now(timezone.utc).isoformat()
    repo = _get(bp, "meta", "repository", default="Unknown Repository") or "Unknown Repository"
    style = (_get(bp, "meta", "architecture_style")
             or _get(bp, "decisions", "architectural_style", "title")
             or "Not determined")

    lines = []

    # Header
    lines.append(f"# {h1}")
    lines.append("")
    lines.append(f"> Architecture guidance for **{repo}**")
    lines.append(f"> Style: {style}")
    lines.append(f"> Generated: {timestamp}")
    lines.append("")

    # Executive Summary
    summary = _get(bp, "meta", "executive_summary")
    if summary:
        lines.append("## Overview")
        lines.append("")
        lines.append(summary)
        lines.append("")

    # Architecture style
    ad = _get(bp, "decisions", "architectural_style", default={}) or {}
    if ad.get("chosen"):
        lines.append("## Architecture")
        lines.append("")
        lines.append(f"**Style:** {ad['chosen']}")
        structure = _get(bp, "components", "structure_type")
        if structure:
            lines.append(f"**Structure:** {structure}")
        if ad.get("rationale"):
            lines.append("")
            lines.append(ad["rationale"])
        lines.append("")

    # Decision chain (compact — root + top-level forces). Skips
    # malformed force entries (non-dicts) defensively.
    dc = _get(bp, "decisions", "decision_chain", default={}) or {}
    if dc.get("root"):
        lines.append(f"**Root constraint:** {dc['root']}")
        for f in _cap(dc.get("forces") or [], 5):
            if not isinstance(f, dict):
                continue
            lines.append(f"- → {f.get('decision', '')}")
        lines.append("")

    # Trade-offs summary (top 3). Skips malformed entries (non-dicts).
    trade_offs = _get(bp, "decisions", "trade_offs", default=[]) or []
    valid_trade_offs = [to for to in trade_offs if isinstance(to, dict)]
    if valid_trade_offs:
        lines.append("**Key trade-offs:**")
        for to in _cap(valid_trade_offs, 3):
            accept = to.get("accept", "") or to.get("accepted", "")
            benefit = to.get("benefit", "") or to.get("gained", "")
            lines.append(f"- {accept} → {benefit}")
        lines.append("")

    # Deployment
    dep = _as_dict(bp.get("deployment"))
    if dep.get("runtime_environment"):
        lines.append(f"**Runs on:** {dep['runtime_environment']}")
        if dep.get("compute_services"):
            lines.append(f"**Compute:** {', '.join(_as_list(dep['compute_services']))}")
        if dep.get("ci_cd"):
            cleaned = [_clean_str_item(x) for x in dep["ci_cd"]]
            lines.append(f"**CI/CD:** {', '.join(cleaned)}")
        lines.append("")

    # Data Models — concise summary; full lifecycle lives in
    # .claude/rules/data-models.md (rendered by _build_data_models_rule).
    # Section is elided entirely on blueprints with no data surface.
    # Order: AI-written overview, models (most-referenced first), stores
    # (most-data first). Models lead because that's what an editor agent
    # reaches for; stores are reference material.
    data_models = _sort_data_models(bp.get("data_models") or [])
    persistence_stores = _sort_persistence_stores(bp.get("persistence_stores") or [])
    overview = bp.get("data_overview") or ""
    if data_models or persistence_stores:
        lines.append("## Data Models")
        lines.append("")
        if isinstance(overview, str) and overview.strip():
            lines.append(overview.strip())
            lines.append("")
        if data_models:
            lines.append(
                "**Models** (full lifecycle in "
                "[`.claude/rules/data-models.md`](.claude/rules/data-models.md)):"
            )
            for m in _cap(data_models, 8):
                lines.append(
                    f"- `{m.get('name','')}` ({m.get('kind','')}) — `{m.get('location','')}`"
                )
            if len(data_models) > 8:
                lines.append(
                    f"- _… {len(data_models) - 8} more in "
                    f"[`.claude/rules/data-models.md`](.claude/rules/data-models.md)_"
                )
            lines.append("")
        if persistence_stores:
            lines.append("**Stores:**")
            for s in persistence_stores:
                name = s.get("name", "")
                engine = s.get("engine", "")
                role = s.get("role", "")
                owned = s.get("owned_models") or []
                meta_parts = [p for p in (engine, f"role: {role}" if role else "") if p]
                head = f"- `{name}`"
                if meta_parts:
                    head += f" ({', '.join(meta_parts)})"
                if owned:
                    head += f" — owns: {', '.join(owned)}"
                lines.append(head)
            lines.append("")

    # Architecture Diagram
    diagram = bp.get("architecture_diagram") or ""
    if diagram:
        lines.append("## Architecture Diagram")
        lines.append("")
        lines.append("```mermaid")
        lines.append(diagram.strip())
        lines.append("```")
        lines.append("")

    # Workspace Topology (monorepo whole-mode blueprints)
    wt = bp.get("workspace_topology") or {}
    if wt and (wt.get("members") or wt.get("edges")):
        ws_type = wt.get("type", "workspace")
        members = wt.get("members") or []
        edges = wt.get("edges") or []
        cycles = wt.get("cycles") or []
        magnets = wt.get("dependency_magnets") or []
        lines.append(f"## Workspace Topology ({ws_type}, {len(members)} workspaces)")
        lines.append("")
        if edges:
            lines.append("```mermaid")
            lines.append("graph LR")
            # Group members by role if available so mermaid node shapes hint at it
            for m in members:
                name = m.get("name", "")
                role = (m.get("role") or "").lower()
                if not name:
                    continue
                safe = name.replace('"', "'")
                if role == "app":
                    lines.append(f'  {safe}(["{safe}"])')
                elif role == "lib":
                    lines.append(f'  {safe}["{safe}"]')
                else:
                    lines.append(f'  {safe}("{safe}")')
            for e in edges:
                frm, to = e.get("from"), e.get("to")
                if frm and to:
                    count = e.get("count")
                    label = f"|{count}|" if count else ""
                    lines.append(f"  {frm} --> {label}{to}")
            lines.append("```")
            lines.append("")
        if members:
            apps = [m for m in members if (m.get("role") or "").lower() == "app"]
            libs = [m for m in members if (m.get("role") or "").lower() in ("lib", "library")]
            other = [m for m in members if m not in apps and m not in libs]
            if apps:
                lines.append("**Apps:** " + ", ".join(f"`{m.get('name')}`" for m in apps))
            if libs:
                lines.append("**Shared libraries:** " + ", ".join(f"`{m.get('name')}`" for m in libs))
            if other:
                lines.append("**Other:** " + ", ".join(f"`{m.get('name')}`" for m in other))
            lines.append("")
        if cycles:
            lines.append("**Cycles detected:**")
            for c in cycles:
                path = " → ".join(c) if isinstance(c, list) else str(c)
                lines.append(f"- `{path}`")
            lines.append("")
        elif members:
            lines.append("_No cross-workspace cycles detected._")
            lines.append("")
        if magnets:
            lines.append("**Dependency magnets** (high fan-in workspaces):")
            for m in magnets:
                lines.append(f"- `{m.get('name')}` (in_degree = {m.get('in_degree', '?')})")
            lines.append("")


    # Commands — only the essential subset (build / test / lint / fmt /
    # run / serve / up) at the root. Full catalog lives in technology.md
    # so a project with 35 make targets doesn't bloat session context.
    run_commands = _get(bp, "technology", "run_commands", default={}) or {}
    if run_commands:
        essential = _essential_commands(run_commands)
        lines.append("## Commands")
        lines.append("")
        if essential:
            lines.append("```bash")
            for cmd_name, cmd_value in essential.items():
                lines.append(f"# {cmd_name}")
                lines.append(cmd_value)
            lines.append("```")
            lines.append("")
        if len(run_commands) > len(essential):
            lines.append(
                f"_Full catalog ({len(run_commands)} commands) in "
                f"[`.claude/rules/technology.md`](.claude/rules/technology.md)._"
            )
            lines.append("")

    # Deep links into topic files. Only list the files we actually emit
    # (some are conditional on blueprint content) so this section never
    # advertises a file that doesn't exist on disk.
    available_topics: list[tuple[str, str]] = [
        ("architecture", "Components, file placement, naming conventions"),
        ("patterns", "Communication patterns, integrations, key decisions, trade-offs (with violation signals)"),
        ("technology", "Tech stack, project structure, code templates, testing tooling"),
        ("data-models", "Persistence stores, data models, per-model lifecycle (how to add/modify/read, backups, tests)"),
        ("guidelines", "Implementation guidelines for existing capabilities"),
        ("pitfalls", "Documented traps with evidence + fix direction"),
        ("dev-rules", "Coding-time imperatives (patterns, anti-patterns, boundaries, wiring)"),
        ("infrastructure", "CI / signing / distribution / secrets / env setup / registry auth"),
        ("enforcement", "Every rule the pre-edit hook + plan/commit classifier consults, grouped by severity"),
        ("frontend", "UI architecture, state, routing (when applicable)"),
    ]
    # Filter to topics that have backing data in the blueprint. The
    # enforcement topic is always advertised (even when blueprint doesn't
    # describe it directly) — its presence is determined by rules.json
    # / platform_rules.json existence at render time.
    has_topic = {
        "architecture": bool(_get(bp, "components", "components") or _get(bp, "architecture_rules", "file_placement_rules")),
        "patterns": bool(_get(bp, "communication", "patterns") or _get(bp, "decisions", "key_decisions") or _get(bp, "decisions", "trade_offs")),
        "technology": bool(_get(bp, "technology", "stack") or _get(bp, "technology", "project_structure") or _get(bp, "technology", "templates")),
        "data-models": bool(bp.get("data_models") or bp.get("persistence_stores")),
        "guidelines": bool(bp.get("implementation_guidelines")),
        "pitfalls": bool(bp.get("pitfalls")),
        "dev-rules": bool(bp.get("development_rules")),
        "infrastructure": bool(bp.get("infrastructure_rules")),
        "enforcement": True,
        "frontend": bool(_as_dict(bp.get("frontend")).get("framework")),
    }

    lines.append("## Architectural Rules")
    lines.append("")
    lines.append("Detailed rules live as topic files under `.claude/rules/`. Read the relevant one when the task touches that surface:")
    lines.append("")
    for topic, blurb in available_topics:
        if has_topic.get(topic):
            if topic == "enforcement":
                lines.append(
                    f"- [`.claude/rules/enforcement/index.md`]"
                    f"(.claude/rules/enforcement/index.md) — {blurb}"
                )
            else:
                lines.append(f"- [`.claude/rules/{topic}.md`](.claude/rules/{topic}.md) — {blurb}")
    lines.append("")

    # Enforcement Rules — pointer + brief explanation. The full browsable
    # rule set is rendered as `.claude/rules/enforcement/` (index +
    # by-topic/ + universal.md), also linked in the Architectural Rules
    # block above. Source of truth on disk: .archie/rules.json +
    # .archie/platform_rules.json.
    lines.append("## Enforcement Rules")
    lines.append("")
    lines.append(
        "[`.claude/rules/enforcement/index.md`](.claude/rules/enforcement/index.md) "
        "indexes every rule, grouped by topic and by path glob. Load only the topic "
        "file(s) relevant to the file you're editing — universal anti-patterns sit in "
        "`enforcement/universal.md`. The pre-edit hook (`PRE_VALIDATE_HOOK`) and "
        "plan/commit classifier (`align_check.py`) read "
        "[`.archie/rules.json`](.archie/rules.json) directly; the markdown is for "
        "agent/human browsing only."
    )
    lines.append("")

    # Per-folder context — intent layer files. Claude Code auto-loads the
    # nearest CLAUDE.md, so just naming the convention is enough.
    lines.append("## Per-folder Context")
    lines.append("")
    lines.append(
        "Every meaningful folder has its own `CLAUDE.md` (Archie's intent layer). "
        "Claude Code auto-loads the nearest one, so when editing a file under "
        "`some/component/`, look there first for the local invariants, anti-patterns, "
        "and adjacent code that uses the same shape."
    )
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Auto-generated from structured architecture analysis. Place in project root.*")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public body generators.
#
# Both produce the same blueprint-derived body, branded with the
# corresponding filename in the H1. Used by:
#   - generate_all()  → writes AGENTS.md to disk (canonical)
#   - serve_command   → renders CLAUDE.md content for the viewer tab
#   - external tests / tooling
#
# CLAUDE.md on disk is NOT this body — it's a static pointer (see
# _CLAUDE_POINTER below). The viewer still calls generate_claude_md() to
# preview the rich markdown; that's a display concern, not a write target.
# ---------------------------------------------------------------------------

def generate_agents_md(bp: dict) -> str:
    """Generate the canonical agent-context body for AGENTS.md."""
    return _generate_agent_body(bp, h1="AGENTS.md")


def generate_claude_md(bp: dict) -> str:
    """Generate the same body branded as CLAUDE.md.

    Kept so the viewer and any external tooling that rendered "blueprint
    → CLAUDE.md preview" keeps working byte-for-byte. The actual
    on-disk CLAUDE.md is a pointer; this function is a render helper.
    """
    return _generate_agent_body(bp, h1="CLAUDE.md")


# ---------------------------------------------------------------------------
# CLAUDE.md (on-disk pointer)
#
# AGENTS.md is the vendor-neutral standard read by Cursor, Codex, Aider,
# Continue, Cline, Cody, and Claude Code itself. It carries the canonical
# blueprint-derived guidance. CLAUDE.md on disk redirects there so any
# Claude Code session that auto-loads CLAUDE.md is told where the truth
# lives in one short line — no duplication, no drift.
# ---------------------------------------------------------------------------

_CLAUDE_POINTER = """# CLAUDE.md

This project's canonical agent context lives in **[AGENTS.md](./AGENTS.md)**.

`AGENTS.md` is the vendor-neutral standard (Cursor, Codex, Aider, Continue,
Cline, Cody — and Claude Code itself read it). Treat it as the source of
truth for architecture, patterns, commands, and enforcement rules.
Per-folder context still lives in nested `CLAUDE.md` files (Archie's
intent layer) and applies to any agent regardless of vendor.
"""


# Prefix → topic fallback for rules without an explicit `topic` field.
# Used during the transition window for legacy rules.json files written
# before Step 6 began emitting `topic`. New rules should always carry topic.
_PREFIX_TO_TOPIC_FALLBACK = {
    "rx-": "concurrency",
    "combine-": "concurrency",
    "nav-": "navigation",
    "ui-": "ui",
    "swiftui-": "ui",
    "snapkit-": "ui",
    "rswift-": "ui",
    "firebase-": "data-access",
    "mapbox-": "mapping",
    "map-": "mapping",
    "layer-": "layering",
    "file-placement-": "layering",
    "extension-filename-": "layering",
    "arch-": "layering",
    "model-": "layering",
    "svc-": "services",
    "sing-": "services",
    "filter-": "services",
    "dep-": "dependencies",
    "build-": "dependencies",
    "secret-": "security",
    "gdpr-": "security",
    "testing-": "testing",
    "res-": "resources",
    "loc-": "resources",
    "god-controller-": "complexity",
    "erosion-": "complexity",
    "decay-": "quality",
}


def _slugify_topic(value: str) -> str:
    """Lowercase, collapse whitespace/underscores into single hyphens, strip."""
    s = value.strip().lower()
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"[^a-z0-9-]", "", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "misc"


def _topic_for_rule(rule: dict) -> str:
    """Resolve a rule's topic. Prefer explicit `topic` field, fall back to
    matching the longest known prefix in `_PREFIX_TO_TOPIC_FALLBACK`. Unknown
    rules go to `misc`."""
    explicit = rule.get("topic")
    if isinstance(explicit, str) and explicit.strip():
        return _slugify_topic(explicit)
    rid = rule.get("id")
    if not isinstance(rid, str):
        rid = ""
    # Match longest prefix first so `file-placement-` wins over `file-`.
    for prefix in sorted(_PREFIX_TO_TOPIC_FALLBACK, key=len, reverse=True):
        if rid.startswith(prefix):
            return _PREFIX_TO_TOPIC_FALLBACK[prefix]
    return "misc"


def _severity_label_for_render(rule: dict) -> str:
    """Resolve a rule's severity_class with backward-compat fallback to legacy
    `severity` ("error" → mechanical_violation, "warn" → tradeoff_undermined)."""
    sc = rule.get("severity_class")
    if sc:
        return sc
    if rule.get("severity") == "error":
        return "mechanical_violation"
    return "tradeoff_undermined"


_SEVERITY_RENDER_ORDER = [
    "decision_violation",
    "pitfall_triggered",
    "mechanical_violation",
    "tradeoff_undermined",
    "pattern_divergence",
]

_SEVERITY_HEADINGS = {
    "decision_violation": "Decision Violations (block)",
    "pitfall_triggered": "Pitfalls (block)",
    "mechanical_violation": "Mechanical Violations (block)",
    "tradeoff_undermined": "Tradeoff Signals (warn)",
    "pattern_divergence": "Pattern Divergence (inform)",
}


def _render_one_enforcement_rule(rule: dict) -> list[str]:
    rid = rule.get("id", "?")
    sev_class = _severity_label_for_render(rule)
    desc = rule.get("description", "")
    why = rule.get("why") or rule.get("rationale") or ""
    example = rule.get("example") or ""
    source = rule.get("source", "")
    triggers = rule.get("triggers") or {}
    applies_to = rule.get("applies_to", "")
    check = rule.get("check", "")

    out = [f"### `{rid}` — {desc}"]
    out.append("")
    meta_bits = []
    if source:
        meta_bits.append(f"*source: `{source}`*")
    if applies_to:
        meta_bits.append(f"*scope: `{applies_to}`*")
    if check:
        meta_bits.append(f"*check: `{check}`*")
    if meta_bits:
        out.append(" · ".join(meta_bits))
        out.append("")
    if why:
        out.append(f"**Why:** {why}")
        out.append("")
    if example:
        out.append("**Example:**")
        out.append("")
        out.append("```")
        out.append(example)
        out.append("```")
        out.append("")
    # Triggers — surface path_glob + code_shape for new-shape rules
    if isinstance(triggers, dict):
        path_globs = triggers.get("path_glob") or []
        if isinstance(path_globs, str):
            path_globs = [path_globs]
        if path_globs:
            out.append("**Path glob:** " + ", ".join(f"`{g}`" for g in path_globs))
            out.append("")
        code_shapes = triggers.get("code_shape") or []
        if isinstance(code_shapes, list) and code_shapes:
            out.append("<details><summary>Code-shape trigger</summary>")
            out.append("")
            out.append("```json")
            out.append(json.dumps(code_shapes, indent=2))
            out.append("```")
            out.append("")
            out.append("</details>")
            out.append("")
    return out


def _render_topic_file(topic: str, rules: list[dict]) -> str:
    """Render a single by-topic markdown file. Rules are severity-grouped
    in the same order as universal.md."""
    by_severity: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        by_severity[_severity_label_for_render(r)].append(r)
    lines = [f"# Enforcement: {topic} ({len(rules)} rule"
             f"{'s' if len(rules) != 1 else ''})", ""]
    lines.append(
        "Topic file. Loaded on demand when an agent works on something "
        f"in the `{topic}` area. The pre-edit hook reads "
        "`.archie/rules.json` directly — this file is for browsing/context only."
    )
    lines.append("")
    for sev in _SEVERITY_RENDER_ORDER:
        bucket = by_severity.get(sev) or []
        if not bucket:
            continue
        lines.append(f"## {_SEVERITY_HEADINGS[sev]}")
        lines.append("")
        for r in bucket:
            lines.extend(_render_one_enforcement_rule(r))
    return "\n".join(lines).rstrip() + "\n"


def _render_universal_file(rules: list[dict]) -> str:
    """Render the universal.md file holding Archie-baked platform rules."""
    by_severity: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        by_severity[_severity_label_for_render(r)].append(r)
    lines = [f"# Universal Enforcement ({len(rules)} rule"
             f"{'s' if len(rules) != 1 else ''})", ""]
    lines.append(
        "Anti-patterns shipped with Archie that apply to every project "
        "regardless of stack. These come from `platform_rules.json`, not "
        "from your project's `rules.json`."
    )
    lines.append("")
    for sev in _SEVERITY_RENDER_ORDER:
        bucket = by_severity.get(sev) or []
        if not bucket:
            continue
        lines.append(f"## {_SEVERITY_HEADINGS[sev]}")
        lines.append("")
        for r in bucket:
            lines.extend(_render_one_enforcement_rule(r))
    return "\n".join(lines).rstrip() + "\n"


def _build_index_file(
    project_topics: dict[str, list[dict]],
    universal_rules: list[dict],
    all_rules: list[dict],
) -> str:
    """Build enforcement/index.md with topic table + path-glob lookup table."""
    total = sum(len(v) for v in project_topics.values()) + len(universal_rules)
    lines = ["# Enforcement Rules — Index", ""]
    lines.append(
        f"This project has {total} rule{'s' if total != 1 else ''} "
        f"across {len(project_topics)} project topic"
        f"{'s' if len(project_topics) != 1 else ''}. Load only the topic "
        "file(s) relevant to your task. Universal Archie anti-patterns "
        "live in `universal.md` and apply to every project."
    )
    lines.append("")

    # By-topic table
    lines.append("## By topic")
    lines.append("")
    lines.append("| Topic | File | Rules |")
    lines.append("|-------|------|-------|")
    for topic in sorted(project_topics):
        n = len(project_topics[topic])
        lines.append(f"| {topic} | by-topic/{topic}.md | {n} |")
    if universal_rules:
        lines.append(f"| Universal | universal.md | {len(universal_rules)} |")
    lines.append("")

    # By-path table — invert path_glob → set of topics
    glob_to_topics: dict[str, set[str]] = defaultdict(set)
    for r in all_rules:
        triggers = r.get("triggers") or {}
        if not isinstance(triggers, dict):
            continue
        globs = triggers.get("path_glob") or []
        if isinstance(globs, str):
            globs = [globs]
        topic = (
            "universal" if r.get("_archie_source") == "platform"
            else _topic_for_rule(r)
        )
        for g in globs:
            if isinstance(g, str) and g:
                glob_to_topics[g].add(topic)

    if glob_to_topics:
        lines.append("## By path")
        lines.append("")
        lines.append(
            "When editing a file matching one of these globs, load the "
            "listed topics first."
        )
        lines.append("")
        lines.append("| Path glob | Topics to load |")
        lines.append("|-----------|----------------|")
        for g in sorted(glob_to_topics):
            topics = ", ".join(sorted(glob_to_topics[g]))
            lines.append(f"| `{g}` | {topics} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def build_enforcement_directory(rules: list[dict]) -> dict[str, str]:
    """Build the enforcement/ directory file map.

    Splits rules by `_archie_source` into project (→ by-topic/) and platform
    (→ universal.md) buckets, groups project rules by topic (resolved via
    `_topic_for_rule`), and emits an index file with a topic table plus a
    path-glob-keyed lookup table.

    Returns a dict mapping relative paths (e.g. `enforcement/index.md`,
    `enforcement/by-topic/concurrency.md`, `enforcement/universal.md`) to
    file contents. Returns `{}` for an empty rule list.
    """
    valid = [r for r in rules if isinstance(r, dict) and r.get("id")]
    if not valid:
        return {}

    project_topics: dict[str, list[dict]] = defaultdict(list)
    universal_rules: list[dict] = []
    for r in valid:
        if r.get("_archie_source") == "platform":
            universal_rules.append(r)
        else:
            project_topics[_topic_for_rule(r)].append(r)

    out: dict[str, str] = {}
    for topic, bucket in project_topics.items():
        out[f"enforcement/by-topic/{topic}.md"] = _render_topic_file(topic, bucket)
    if universal_rules:
        out["enforcement/universal.md"] = _render_universal_file(universal_rules)
    out["enforcement/index.md"] = _build_index_file(project_topics, universal_rules, valid)
    return out


# ---------------------------------------------------------------------------
# Main orchestrator
# ---------------------------------------------------------------------------

def generate_all(bp: dict, enforcement_rules: list[dict] | None = None) -> dict:
    """Generate all output files from a blueprint dict.

    `enforcement_rules` is the merged contents of `.archie/rules.json` +
    `.archie/platform_rules.json` — when present, an additional
    `.claude/rules/enforcement/` directory (index.md + by-topic/ +
    universal.md) gets emitted with every rule grouped by severity_class.
    Pass `None` (or omit) when rendering a blueprint without access to those files.

    Returns {path: content} for every output file.
    """
    rule_files = []

    builders = [
        _build_architecture_rule,
        _build_patterns_rule,
        _build_technology_rule,
        _build_frontend_rule,
        _build_guidelines_rule,
        _build_pitfalls_rule,
        _build_dev_rules_rule,
        _build_infrastructure_rule,
        _build_data_models_rule,
    ]

    for builder in builders:
        result = builder(bp)
        if result is not None:
            rule_files.append(result)

    # AGENTS.md is the canonical, blueprint-derived doc (vendor-neutral
    # standard read by Cursor, Codex, Aider, Continue, Cline, Cody, and
    # Claude Code). CLAUDE.md is a static pointer (full-overwrite, not
    # mergeable) so any Claude Code session is told where the truth lives
    # without paying duplicate tokens.
    files = {
        "AGENTS.md": generate_agents_md(bp),
        "CLAUDE.md": _CLAUDE_POINTER,
    }

    for rf in rule_files:
        topic = rf["topic"]
        files[f".claude/rules/{topic}.md"] = _render_claude(rf)

    # Enforcement rules topic — only emitted when caller passes the rules
    # list (typically loaded from .archie/rules.json + platform_rules.json).
    if enforcement_rules:
        directory = build_enforcement_directory(enforcement_rules)
        for rel_path, content in directory.items():
            files[f".claude/rules/{rel_path}"] = content

    return files


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 renderer.py /path/to/project", file=sys.stderr)
        sys.exit(1)

    project_root = Path(sys.argv[1]).resolve()

    global _COMPREHENSIVE
    _COMPREHENSIVE = "--comprehensive" in sys.argv

    blueprint_path = project_root / ".archie" / "blueprint.json"

    if not blueprint_path.exists():
        print(f"Error: {blueprint_path} not found", file=sys.stderr)
        sys.exit(1)

    bp = json.loads(blueprint_path.read_text())

    # Load enforcement rules from .archie/rules.json + platform_rules.json
    # so the renderer can emit a browsable enforcement/ directory.
    # Both files are optional; missing-or-malformed cases produce no
    # enforcement/ files and don't fail the render.
    enforcement_rules: list[dict] = []
    for fname, src in (("rules.json", "project"), ("platform_rules.json", "platform")):
        path = project_root / ".archie" / fname
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        items = data if isinstance(data, list) else data.get("rules", [])
        if isinstance(items, list):
            for r in items:
                if isinstance(r, dict):
                    r.setdefault("_archie_source", src)
                    enforcement_rules.append(r)

    files = generate_all(bp, enforcement_rules=enforcement_rules)

    # Write all files. CLAUDE.md and AGENTS.md may coexist with hand-authored
    # content — those go through render_mergeable which preserves user content
    # outside Archie's generated block.
    for rel_path, content in files.items():
        full_path = project_root / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)

        if rel_path in MERGEABLE_FILES:
            existed = full_path.exists()
            had_markers = existed and ARCHIE_MARKER_START in full_path.read_text()
            merged = render_mergeable(full_path, content)
            full_path.write_text(merged)
            if not existed:
                status = "new"
            elif had_markers:
                status = "updated Archie block"
            else:
                status = "appended Archie block (user content preserved)"
            print(f"  {rel_path}: {status}")
        else:
            full_path.write_text(content)
            print(f"  Generated {rel_path} ({content.count(chr(10)) + 1} lines)")

    print(f"\nDone: {len(files)} files generated in {project_root}")


if __name__ == "__main__":
    main()
