#!/usr/bin/env python3
"""Archie development studio — deterministic issue-tracking engine.

Subcommands (Python never runs git — it only writes files):
  python3 studio.py init  /path/to/repo
  python3 studio.py new   /path/to/repo --title "..." --type feature --label backend
  python3 studio.py move  /path/to/repo ISS-NNN <status>
  python3 studio.py index /path/to/repo
  python3 studio.py next  /path/to/repo

Scaffolds and maintains `.archie/issues/` in the target project. The INDEX.md
tables are always DERIVED from ticket frontmatter — never hand-edited.

Zero dependencies beyond Python 3.9+ stdlib.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

STATUSES = ["planned", "in-progress", "in-review", "done", "blocked"]


def parse_frontmatter(text: str) -> dict | None:
    """Parse a minimal YAML frontmatter block (--- ... ---) at the top of text.

    Supports scalars (`key: value`) and inline lists (`key: [a, b]`). Returns
    None if no frontmatter block is present. Robust to a leading BOM/whitespace.
    """
    s = text.lstrip("﻿")
    if not s.startswith("---"):
        return None
    lines = s.splitlines()
    # first line is the opening ---; find the closing ---
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return None
    fm: dict = {}
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, raw = line.partition(":")
        key = key.strip()
        val = raw.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fm[key] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        else:
            fm[key] = val
    return fm


def issues_dir(root: Path) -> Path:
    return root / ".archie" / "issues"


def iter_tickets(issues: Path) -> list[dict]:
    """Parse every ticket .md across status folders. Skip corrupt files (warn)."""
    tickets: list[dict] = []
    if not issues.exists():
        return tickets
    for status in STATUSES:
        folder = issues / status
        if not folder.is_dir():
            continue
        for path in sorted(folder.glob("*.md")):
            try:
                fm = parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
            except OSError:
                fm = None
            if not fm or "id" not in fm:
                print(f"studio: skip unparseable ticket {path}", file=sys.stderr)
                continue
            fm["_path"] = path
            fm["_folder_status"] = status
            tickets.append(fm)
    return tickets


def next_id(tickets: list[dict], prefix: str) -> str:
    """Return the next zero-padded id (e.g. ISS-012) given existing tickets."""
    pat = re.compile(rf"^{re.escape(prefix)}-(\d+)$")
    nums = [int(m.group(1)) for t in tickets if (m := pat.match(str(t.get("id", ""))))]
    return f"{prefix}-{(max(nums) + 1) if nums else 1:03d}"


def _row(t: dict, cols: list[str]) -> str:
    def cell(key: str) -> str:
        v = t.get(key, "")
        if isinstance(v, list):
            v = ", ".join(v)
        return str(v).replace("|", "\\|") or "—"
    return "| " + " | ".join(cell(c) for c in cols) + " |"


def render_index(tickets: list[dict]) -> str:
    by = {s: [t for t in tickets if t.get("status") == s] for s in STATUSES}
    next_iss = next_id(tickets, "ISS")
    next_epic = next_id(tickets, "EPIC")  # no ISS id matches the EPIC pattern, so this yields EPIC-001 until epics exist
    lines: list[str] = []
    lines.append("# Issue Index")
    lines.append("")
    lines.append("> Generated by `studio.py index` — do not edit by hand.")
    lines.append("")
    lines.append(f"- Next issue: {next_iss}")
    lines.append(f"- Next epic: {next_epic}")
    lines.append("")
    lines.append("## Blocked")
    if by["blocked"]:
        lines.append("| ID | Title | Branch |")
        lines.append("| --- | --- | --- |")
        for t in by["blocked"]:
            lines.append(_row(t, ["id", "title", "branch"]))
    else:
        lines.append("None.")
    lines.append("")
    lines.append("## Active")
    active = by["in-progress"] + by["in-review"] + by["planned"]
    lines.append("| ID | Title | Status | Type | Labels | Branch |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for t in active:
        lines.append(_row(t, ["id", "title", "status", "type", "labels", "branch"]))
    if not active:
        lines.append("| — | none | — | — | — | — |")
    lines.append("")
    lines.append("## Done")
    lines.append("| ID | Title | Type | Labels |")
    lines.append("| --- | --- | --- | --- |")
    for t in by["done"][-20:]:
        lines.append(_row(t, ["id", "title", "type", "labels"]))
    if not by["done"]:
        lines.append("| — | none | — | — |")
    lines.append("")
    return "\n".join(lines)


TEMPLATE = """---
id: ISS-NNN
title: Short imperative title
status: planned
labels: []
branch: feature/ISS-NNN-slug
assignee: csaba
created: YYYY-MM-DD
updated: YYYY-MM-DD
type: feature
epic:
---

## Context
Why this work is needed.

## Plan
- [ ] Step one (verifiable)

## Implementation Notes

## Iteration Log
- iter 01 (YYYY-MM-DD HH:MM): what / result / next

## Last Test Run
```
command:
result:
summary:
ran:
```

## Evidence

## Blocker

## Review Notes

## Testing
"""

WORKFLOW_DOC = """# Development Studio Workflow

This project uses Archie's development studio. All issue tracking lives under
`.archie/issues/`. The INDEX.md is generated — never hand-edit it.

## Required Workflow

When asked for any code change, follow these steps in order. Do not skip steps.

1. **Discovery** — read `.archie/issues/INDEX.md`. If a ticket is `blocked`, surface
   it and stop. Check `in-progress/` for overlapping work. Confirm work type
   (feature/bugfix/refactor/chore).
2. **Ticket creation (on `main`)** — `python3 .archie/studio.py new . --title "..."
   --type <type> --label <label>`. Fill Context. Commit `docs(issues): add ISS-NNN
   <title>` and push.
3. **Branch & Plan** — branch `<type>/ISS-NNN-<slug>`. Read `.archie/blueprint.json`
   for the relevant decisions, domain_invariants, pitfalls, components. Write the Plan
   as a checkbox list, annotating which rule/invariant each step preserves.
   `python3 .archie/studio.py move . ISS-NNN in-progress`. Commit `docs(issues): plan
   ISS-NNN`. **Wait for approval.**
4. **Implementation (autonomous loop)** — implement step by step. Archie's
   `pre-validate.sh` hook enforces `rules.json` on every edit; on a block, fix using
   the rule's WHY + EXAMPLE. After each checkbox: append Iteration Log, update Last
   Test Run, mark `[x]`, commit `feat(ISS-NNN): <step>`. Capture evidence into
   `evidence/ISS-NNN/`.
5. **Review** — separate review agent on the diff; findings → Review Notes;
   `move . ISS-NNN in-review`.
6. **Verify** — every acceptance criterion one by one; test touched domain invariants
   concretely. Optionally run `validate.py` + `drift.py`.
7. **Close out** — `move . ISS-NNN done`, write the PR description, commit
   `docs(issues): close ISS-NNN`, open the PR.

## Autonomous Execution

Once a plan is approved, run the loop without pausing between
implement/test/fix/review until ready to close. Stop and ask only when: the plan needs
a material change; a destructive/hard-to-reverse action is required; or after 2
consecutive failed fix attempts on the same root cause → set `status: blocked`, write
the Blocker section, and stop.

## Ralph Loop Entry

When invoked without a specific task: read INDEX.md; if anything is `blocked`, stop and
surface it; else continue the topmost `in-progress` ticket from its first unchecked
`[ ]`; else promote the topmost `planned` ticket; else report idle. Every ticket is
self-contained — never rely on conversation memory.

## Hard Rules

- Never start coding without a ticket. Never skip reading INDEX.md first.
- One ticket = one branch = one logical change.
- Always update the index via `studio.py move` / `studio.py index` — never hand-edit it.
- Commit after every checked Plan step.
- If `.archie/blueprint.json` is missing, run `/archie-deep-scan` first — the loop
  works without it but with no architectural enforcement or guidance.
"""


def write_index(root: Path) -> None:
    issues = issues_dir(root)
    (issues / "INDEX.md").write_text(render_index(iter_tickets(issues)), encoding="utf-8")


STUDIO_START = "<!-- ARCHIE:STUDIO:START -->"
STUDIO_END = "<!-- ARCHIE:STUDIO:END -->"
STUDIO_BLOCK = f"""{STUDIO_START}
## Development Studio
This project uses Archie's development studio for issue tracking and the agentic
development loop. **Before any code change, read `.archie/issues/WORKFLOW.md`** — it
defines the required workflow, ticket lifecycle, and autonomous execution rules.
{STUDIO_END}"""


def patch_agents_md(root: Path) -> None:
    path = root / "AGENTS.md"
    if not path.exists():
        path.write_text(STUDIO_BLOCK + "\n", encoding="utf-8")
        return
    content = path.read_text(encoding="utf-8")
    if STUDIO_START in content and STUDIO_END in content:
        pre = content.split(STUDIO_START)[0]
        post = content.split(STUDIO_END, 1)[1]
        content = pre + STUDIO_BLOCK + post
    else:
        sep = "" if content.endswith("\n") else "\n"
        content = content + sep + "\n" + STUDIO_BLOCK + "\n"
    path.write_text(content, encoding="utf-8")


def cmd_init(root: Path) -> None:
    issues = issues_dir(root)
    for sub in STATUSES + ["epics", "evidence"]:
        (issues / sub).mkdir(parents=True, exist_ok=True)
    tmpl = issues / "_TEMPLATE.md"
    if not tmpl.exists():
        tmpl.write_text(TEMPLATE, encoding="utf-8")
    (issues / "WORKFLOW.md").write_text(WORKFLOW_DOC, encoding="utf-8")
    write_index(root)
    patch_agents_md(root)
    print(f"studio: initialized {issues}", file=sys.stderr)


def _slugify(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return "-".join(s.split("-")[:6]) or "ticket"


def cmd_new(root: Path, *, title: str, type_: str, labels: list[str], today: str) -> str:
    issues = issues_dir(root)
    if not issues.exists():
        cmd_init(root)
    tid = next_id(iter_tickets(issues), "ISS")
    slug = _slugify(title)
    labels_yaml = "[" + ", ".join(labels) + "]"
    body = (
        f"---\n"
        f"id: {tid}\n"
        f"title: {title}\n"
        f"status: planned\n"
        f"labels: {labels_yaml}\n"
        f"branch: {type_}/{tid}-{slug}\n"
        f"assignee: csaba\n"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"type: {type_}\n"
        f"epic:\n"
        f"---\n\n"
        f"## Context\n\n## Plan\n- [ ] \n\n## Implementation Notes\n\n"
        f"## Iteration Log\n\n## Last Test Run\n\n## Evidence\n\n"
        f"## Blocker\n\n## Review Notes\n\n## Testing\n"
    )
    (issues / "planned" / f"{tid}-{slug}.md").write_text(body, encoding="utf-8")
    write_index(root)
    print(f"studio: created {tid}", file=sys.stderr)
    return tid


def _find_ticket_path(issues: Path, tid: str) -> Path | None:
    for t in iter_tickets(issues):
        if t.get("id") == tid:
            return t["_path"]
    return None


def _set_frontmatter_status(text: str, status: str) -> str:
    """Set ``status:`` within the leading ``--- ... ---`` frontmatter only.

    If the frontmatter has a ``status:`` line, rewrite it; otherwise insert one.
    The document body is never touched.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        # No frontmatter block — prepend one rather than mutate the body.
        fm = ["---", f"status: {status}", "---", ""]
        return "\n".join(fm + lines)
    # Find the closing fence of the frontmatter block.
    close = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            close = i
            break
    if close is None:
        fm = ["---", f"status: {status}", "---", ""]
        return "\n".join(fm + lines)
    for i in range(1, close):
        if re.match(r"^status:", lines[i]):
            lines[i] = f"status: {status}"
            return "\n".join(lines)
    # No status line in frontmatter — insert one just after the opening fence.
    lines.insert(1, f"status: {status}")
    return "\n".join(lines)


def cmd_move(root: Path, tid: str, status: str) -> None:
    if status not in STATUSES:
        print(f"studio: unknown status '{status}' (allowed: {', '.join(STATUSES)})",
              file=sys.stderr)
        sys.exit(2)
    issues = issues_dir(root)
    src = _find_ticket_path(issues, tid)
    if src is None:
        print(f"studio: ticket {tid} not found", file=sys.stderr)
        sys.exit(2)
    text = src.read_text(encoding="utf-8")
    text = _set_frontmatter_status(text, status)
    dest = issues / status / src.name
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and dest != src:
        print(f"studio: destination {dest} already exists", file=sys.stderr)
        sys.exit(2)
    dest.write_text(text, encoding="utf-8")
    if dest != src:
        src.unlink()
    write_index(root)
    print(f"studio: moved {tid} -> {status}", file=sys.stderr)


def cmd_next(root: Path) -> dict:
    """Return the next action per Ralph priority. Prints JSON to stdout."""
    tickets = iter_tickets(issues_dir(root))
    by = {s: [t for t in tickets if t.get("status") == s] for s in STATUSES}

    def pick(lst):
        return sorted(lst, key=lambda t: str(t.get("id")))[0]

    if by["blocked"]:
        t = pick(by["blocked"])
        result = {"action": "blocked", "id": t["id"], "title": t.get("title")}
    elif by["in-progress"]:
        t = pick(by["in-progress"])
        result = {"action": "continue", "id": t["id"], "title": t.get("title"),
                  "path": str(t["_path"])}
    elif by["planned"]:
        t = pick(by["planned"])
        result = {"action": "promote", "id": t["id"], "title": t.get("title"),
                  "path": str(t["_path"])}
    else:
        result = {"action": "idle"}
    json.dump(result, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return result


def _flag(argv: list[str], name: str, default=None):
    for i, a in enumerate(argv):
        if a == name and i + 1 < len(argv):
            return argv[i + 1]
    return default


def _flags_all(argv: list[str], name: str) -> list[str]:
    out = []
    for i, a in enumerate(argv):
        if a == name and i + 1 < len(argv):
            out.append(argv[i + 1])
    return out


def _today() -> str:
    from datetime import date
    return date.today().isoformat()


def _usage() -> None:
    print(
        "Usage:\n"
        "  studio.py init  <repo>\n"
        "  studio.py new   <repo> --title \"...\" --type <type> [--label L ...]\n"
        "  studio.py move  <repo> ISS-NNN <status>\n"
        "  studio.py index <repo>\n"
        "  studio.py next  <repo>",
        file=sys.stderr,
    )


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        _usage()
        return 1
    sub = argv[0]
    root = Path(argv[1]).resolve()
    rest = argv[2:]
    if sub == "init":
        cmd_init(root)
    elif sub == "new":
        title = _flag(rest, "--title")
        if not title:
            print("studio: --title required", file=sys.stderr)
            return 2
        cmd_new(root, title=title, type_=_flag(rest, "--type", "feature"),
                labels=_flags_all(rest, "--label"), today=_today())
    elif sub == "move":
        if len(rest) < 2:
            print("studio: move needs ISS-NNN <status>", file=sys.stderr)
            return 2
        cmd_move(root, rest[0], rest[1])
    elif sub == "index":
        write_index(root)
    elif sub == "next":
        cmd_next(root)
    else:
        _usage()
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
